package com.jinchi.app.mapper;

import com.jinchi.app.domain.AppDeviceStatisticDetail;
import com.jinchi.app.domain.AppDeviceStatisticDetailExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
@Mapper
public interface AppDeviceStatisticDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    int countByExample(AppDeviceStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    int deleteByExample(AppDeviceStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into app_device_statistic_detail (code, report_head_code, ",
        "device_name, device_num, ",
        "in_service_num, standby_num, ",
        "recondition_num, scrap_num)",
        "values (#{code,jdbcType=BIGINT}, #{reportHeadCode,jdbcType=BIGINT}, ",
        "#{deviceName,jdbcType=VARCHAR}, #{deviceNum,jdbcType=INTEGER}, ",
        "#{inServiceNum,jdbcType=INTEGER}, #{standbyNum,jdbcType=INTEGER}, ",
        "#{reconditionNum,jdbcType=INTEGER}, #{scrapNum,jdbcType=INTEGER})"
    })
    int insert(AppDeviceStatisticDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    int insertSelective(AppDeviceStatisticDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    List<AppDeviceStatisticDetail> selectByExample(AppDeviceStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppDeviceStatisticDetail record, @Param("example") AppDeviceStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppDeviceStatisticDetail record, @Param("example") AppDeviceStatisticDetailExample example);
}