package com.jinchi.app.mapper;

import com.jinchi.app.domain.AppDeviceStatisticHead;
import com.jinchi.app.domain.AppDeviceStatisticHeadExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
@Mapper
public interface AppDeviceStatisticHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    int countByExample(AppDeviceStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    int deleteByExample(AppDeviceStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    @Insert({
        "insert into \"app_device_statistic_head\" (code, dept_code, ",
        "dept_name, statistical_date, ",
        "total_device, total_in_service, ",
        "total_standby, total_recondition, ",
        "total_scrap)",
        "values (#{code,jdbcType=BIGINT}, #{deptCode,jdbcType=INTEGER}, ",
        "#{deptName,jdbcType=VARCHAR}, #{statisticalDate,jdbcType=TIMESTAMP}, ",
        "#{totalDevice,jdbcType=INTEGER}, #{totalInService,jdbcType=INTEGER}, ",
        "#{totalStandby,jdbcType=INTEGER}, #{totalRecondition,jdbcType=INTEGER}, ",
        "#{totalScrap,jdbcType=INTEGER})"
    })
    int insert(AppDeviceStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    int insertSelective(AppDeviceStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    List<AppDeviceStatisticHead> selectByExample(AppDeviceStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppDeviceStatisticHead record, @Param("example") AppDeviceStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_statistic_head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppDeviceStatisticHead record, @Param("example") AppDeviceStatisticHeadExample example);
}