package com.jinchi.app.mapper;

import com.jinchi.app.domain.AppSpotcheckStatisticDetail;
import com.jinchi.app.domain.AppSpotcheckStatisticDetailExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
@Mapper
public interface AppSpotcheckStatisticDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    int countByExample(AppSpotcheckStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    int deleteByExample(AppSpotcheckStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into app_spotcheck_statistic_detail (code, report_head_code, ",
        "statisitc_date, spotcheck_num, ",
        "anomaly_num)",
        "values (#{code,jdbcType=BIGINT}, #{reportHeadCode,jdbcType=BIGINT}, ",
        "#{statisitcDate,jdbcType=TIMESTAMP}, #{spotcheckNum,jdbcType=INTEGER}, ",
        "#{anomalyNum,jdbcType=INTEGER})"
    })
    int insert(AppSpotcheckStatisticDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    int insertSelective(AppSpotcheckStatisticDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    List<AppSpotcheckStatisticDetail> selectByExample(AppSpotcheckStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppSpotcheckStatisticDetail record, @Param("example") AppSpotcheckStatisticDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_spotcheck_statistic_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppSpotcheckStatisticDetail record, @Param("example") AppSpotcheckStatisticDetailExample example);
}