package com.jinchi.app.mapper;

import com.jinchi.app.domain.BasicAppInfo;
import com.jinchi.app.domain.BasicAppInfoExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface BasicAppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    int countByExample(BasicAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    int deleteByExample(BasicAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_app_info (code, url, ",
        "app_version, creat_time, ",
        "description, os_version)",
        "values (#{code,jdbcType=INTEGER}, #{url,jdbcType=VARCHAR}, ",
        "#{appVersion,jdbcType=VARCHAR}, #{creatTime,jdbcType=TIMESTAMP}, ",
        "#{description,jdbcType=VARCHAR}, #{osVersion,jdbcType=VARCHAR})"
    })
    int insert(BasicAppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    int insertSelective(BasicAppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    List<BasicAppInfo> selectByExample(BasicAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicAppInfo record, @Param("example") BasicAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_app_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicAppInfo record, @Param("example") BasicAppInfoExample example);
}