package com.jinchi.app.mapper;

import com.jinchi.app.domain.BasicInfoQuickPhrases;
import com.jinchi.app.domain.BasicInfoQuickPhrasesExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface BasicInfoQuickPhrasesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoQuickPhrasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoQuickPhrasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_quick_phrases (code, name)",
        "values (#{code,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(BasicInfoQuickPhrases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoQuickPhrases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    List<BasicInfoQuickPhrases> selectByExample(BasicInfoQuickPhrasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoQuickPhrases record, @Param("example") BasicInfoQuickPhrasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_quick_phrases
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoQuickPhrases record, @Param("example") BasicInfoQuickPhrasesExample example);
}