package com.jinchi.app.mapper;

import com.jinchi.app.domain.DevicePatrolPlanRecordItemDetails;
import com.jinchi.app.domain.DevicePatrolPlanRecordItemDetailsExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DevicePatrolPlanRecordItemDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    int countByExample(DevicePatrolPlanRecordItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    int deleteByExample(DevicePatrolPlanRecordItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_patrol_plan_record_item_details (code, plan_record_code, ",
        "model_detail_code, patrol_item, ",
        "patrol_content, main_values, ",
        "main_content)",
        "values (#{code,jdbcType=BIGINT}, #{planRecordCode,jdbcType=BIGINT}, ",
        "#{modelDetailCode,jdbcType=BIGINT}, #{patrolItem,jdbcType=VARCHAR}, ",
        "#{patrolContent,jdbcType=VARCHAR}, #{mainValues,jdbcType=INTEGER}, ",
        "#{mainContent,jdbcType=VARCHAR})"
    })
    int insert(DevicePatrolPlanRecordItemDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    int insertSelective(DevicePatrolPlanRecordItemDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    List<DevicePatrolPlanRecordItemDetails> selectByExample(DevicePatrolPlanRecordItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DevicePatrolPlanRecordItemDetails record, @Param("example") DevicePatrolPlanRecordItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_plan_record_item_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DevicePatrolPlanRecordItemDetails record, @Param("example") DevicePatrolPlanRecordItemDetailsExample example);
}