package com.jinchi.app.mapper;

import com.jinchi.app.domain.DeviceRepairEvaluations;
import com.jinchi.app.domain.DeviceRepairEvaluationsExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DeviceRepairEvaluationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    int countByExample(DeviceRepairEvaluationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceRepairEvaluationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_repair_evaluations (code, item_code, ",
        "item_name, levels, ",
        "repair_code)",
        "values (#{code,jdbcType=BIGINT}, #{itemCode,jdbcType=INTEGER}, ",
        "#{itemName,jdbcType=VARCHAR}, #{levels,jdbcType=INTEGER}, ",
        "#{repairCode,jdbcType=BIGINT})"
    })
    int insert(DeviceRepairEvaluations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    int insertSelective(DeviceRepairEvaluations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    List<DeviceRepairEvaluations> selectByExample(DeviceRepairEvaluationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceRepairEvaluations record, @Param("example") DeviceRepairEvaluationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceRepairEvaluations record, @Param("example") DeviceRepairEvaluationsExample example);
}