package com.jinchi.app.mapper;

import com.jinchi.app.domain.DeviceRepairApplication;
import com.jinchi.app.domain.DeviceRepairApplicationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DeviceRepairApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int countByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int deleteByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int insert(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int insertSelective(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    List<DeviceRepairApplication> selectByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    DeviceRepairApplication selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceRepairApplication record, @Param("example") DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int updateByExample(@Param("record") DeviceRepairApplication record, @Param("example") DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:24:49 CST 2020
     */
    int updateByPrimaryKey(DeviceRepairApplication record);

    List<DeviceRepairApplication> selectBycondition(@Param("sql") String sql);

    int countByCondition(@Param("sql") String sql);
}