package com.jinchi.app.mapper;

import com.jinchi.app.domain.DeviceRepairApplication;
import com.jinchi.app.domain.DeviceRepairApplicationExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DeviceRepairApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    int countByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_repair_application (code, dept_code, ",
        "device_code, device_name, ",
        "fixedassets_code, fault_content, ",
        "report_time, report_people, ",
        "report_phone, receive_time, ",
        "receive_people, receive_phone, ",
        "fault_reason, finish_time, ",
        "evaluation_time, evaluation_result, ",
        "repair_status, emerge_status)",
        "values (#{code,jdbcType=BIGINT}, #{deptCode,jdbcType=INTEGER}, ",
        "#{deviceCode,jdbcType=BIGINT}, #{deviceName,jdbcType=VARCHAR}, ",
        "#{fixedassetsCode,jdbcType=VARCHAR}, #{faultContent,jdbcType=VARCHAR}, ",
        "#{reportTime,jdbcType=TIMESTAMP}, #{reportPeople,jdbcType=INTEGER}, ",
        "#{reportPhone,jdbcType=VARCHAR}, #{receiveTime,jdbcType=TIMESTAMP}, ",
        "#{receivePeople,jdbcType=INTEGER}, #{receivePhone,jdbcType=VARCHAR}, ",
        "#{faultReason,jdbcType=VARCHAR}, #{finishTime,jdbcType=TIMESTAMP}, ",
        "#{evaluationTime,jdbcType=TIMESTAMP}, #{evaluationResult,jdbcType=VARCHAR}, ",
        "#{repairStatus,jdbcType=INTEGER}, #{emergeStatus,jdbcType=INTEGER})"
    })
    int insert(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    int insertSelective(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    List<DeviceRepairApplication> selectByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceRepairApplication record, @Param("example") DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceRepairApplication record, @Param("example") DeviceRepairApplicationExample example);

    List<DeviceRepairApplication> selectBycondition(@Param("sql") String sql);

    int countByCondition(@Param("sql") String sql);
}