package com.jinchi.app.mapper;

import com.jinchi.app.domain.PowerCheckItem;
import com.jinchi.app.domain.PowerCheckItemExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface PowerCheckItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int countByExample(PowerCheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int deleteByExample(PowerCheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int insert(PowerCheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int insertSelective(PowerCheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    List<PowerCheckItem> selectByExample(PowerCheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    PowerCheckItem selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") PowerCheckItem record, @Param("example") PowerCheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByExample(@Param("record") PowerCheckItem record, @Param("example") PowerCheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByPrimaryKeySelective(PowerCheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_item
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByPrimaryKey(PowerCheckItem record);

    List selectBySiteCode(@Param("siteCode") Long siteCode);
}