package com.jinchi.app.mapper;

import com.jinchi.app.domain.PowerCheckModelDetail;
import com.jinchi.app.domain.PowerCheckModelDetailExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface PowerCheckModelDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int countByExample(PowerCheckModelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int deleteByExample(PowerCheckModelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int insert(PowerCheckModelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int insertSelective(PowerCheckModelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    List<PowerCheckModelDetail> selectByExample(PowerCheckModelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    PowerCheckModelDetail selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") PowerCheckModelDetail record, @Param("example") PowerCheckModelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByExample(@Param("record") PowerCheckModelDetail record, @Param("example") PowerCheckModelDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByPrimaryKeySelective(PowerCheckModelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_check_model_detail
     *
     * @mbggenerated Wed Mar 25 13:25:42 CST 2020
     */
    int updateByPrimaryKey(PowerCheckModelDetail record);
}