server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 60000
zuul:
  routes:
    AUTH-SERVICE: /jc/auth/**
    COMMON-SERVICE: /jc/common/**
    REPOAPI-SERVICE: /jc/repo/**
    APP-SERVICE: /jc/app/**
  sensitive-headers: #不填则是清空
spring:
  application:
    name: ZUUL-SERVER
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB