primary:
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      platform: mysql
      url: jdbc:mysql://115.157.192.47:3306/jc_integration_db?userUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT&useAffectedRows=true
      username: root
      password: 123456
    application:
      name: COMMON-SERVICE
secondary:
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      platform: mysql
      url: jdbc:mysql://115.157.192.47:3306/jc_auth_db?userUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT&useAffectedRows=true
      username: root
      password: 123456
    application:
      name: AUTH-SERVICE
server:
  port: 8083
  servlet:
    context-path:
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka