primary:
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      platform: mysql
      url: jdbc:mysql://125.94.71.249:3306/jc_integration_db?userUnicode=true&characterEncoding=UTF8&useSSL=false&useAffectedRows=true&useLegacyDatetimeCode=false&serverTimezone=CTT
      username: root
      password: 123456
      druid:
        test-on-borrow: true
        validationQuery: SELECT 1
        test-while-idle: true
        time-between-eviction-runs-millis: 300000
        #连接池空闲连接的有效时间 ，设置30分钟
        min-evictable-idle-time-millis: 1800000
#      druid:
#       time-between-eviction-runs-millis: 300000
#      #连接池空闲连接的有效时间 ，设置30分钟
#       min-evictable-idle-time-millis: 1800000
    application:
      name: COMMON-SERVICE


secondary:
  spring:
    datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     platform: mysql
     url: jdbc:mysql://125.94.71.249:3306/jc_auth_db?userUnicode=true&characterEncoding=UTF8&useSSL=false&useAffectedRows=true&useLegacyDatetimeCode=false&serverTimezone=CTT
     username: root
     password: 123456
     druid:
       test-on-borrow: true
       validationQuery: SELECT 1
       test-while-idle: true
       time-between-eviction-runs-millis: 300000
        #连接池空闲连接的有效时间 ，设置30分钟
       min-evictable-idle-time-millis: 1800000
    application:
      name: AUTH-SERVICE
server:
  port: 8083
  servlet:
    context-path:
  tomcat:
    max-http-post-size: -1
    max-connections: 10000
  connection-timeout: 10000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: APP-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
app:
  url: http://localhost:8080

logging:
  level:
    root: warn
    com.jinchi.app.mapper: trace
  pattern:
    console: '%p%m%n'