package com.jinchi.app.domain;

public class DeviceRepairAccessory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_accessory.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_accessory.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_accessory.specification
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_accessory.counts
     *
     * @mbggenerated
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_accessory.repair_code
     *
     * @mbggenerated
     */
    private Long repairCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_accessory.units
     *
     * @mbggenerated
     */
    private Byte units;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_accessory
     *
     * @mbggenerated
     */
    public DeviceRepairAccessory(Long code, String name, String specification, Integer counts, Long repairCode, Byte units) {
        this.code = code;
        this.name = name;
        this.specification = specification;
        this.counts = counts;
        this.repairCode = repairCode;
        this.units = units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_accessory
     *
     * @mbggenerated
     */
    public DeviceRepairAccessory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_accessory.code
     *
     * @return the value of device_repair_accessory.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_accessory.code
     *
     * @param code the value for device_repair_accessory.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_accessory.name
     *
     * @return the value of device_repair_accessory.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_accessory.name
     *
     * @param name the value for device_repair_accessory.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_accessory.specification
     *
     * @return the value of device_repair_accessory.specification
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_accessory.specification
     *
     * @param specification the value for device_repair_accessory.specification
     *
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_accessory.counts
     *
     * @return the value of device_repair_accessory.counts
     *
     * @mbggenerated
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_accessory.counts
     *
     * @param counts the value for device_repair_accessory.counts
     *
     * @mbggenerated
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_accessory.repair_code
     *
     * @return the value of device_repair_accessory.repair_code
     *
     * @mbggenerated
     */
    public Long getRepairCode() {
        return repairCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_accessory.repair_code
     *
     * @param repairCode the value for device_repair_accessory.repair_code
     *
     * @mbggenerated
     */
    public void setRepairCode(Long repairCode) {
        this.repairCode = repairCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_accessory.units
     *
     * @return the value of device_repair_accessory.units
     *
     * @mbggenerated
     */
    public Byte getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_accessory.units
     *
     * @param units the value for device_repair_accessory.units
     *
     * @mbggenerated
     */
    public void setUnits(Byte units) {
        this.units = units;
    }
}