package com.jinchi.app.domain;

public class DeviceRepairEvaluations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_evaluations.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_evaluations.item_code
     *
     * @mbggenerated
     */
    private Integer itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_evaluations.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_evaluations.levels
     *
     * @mbggenerated
     */
    private Integer levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_repair_evaluations.repair_code
     *
     * @mbggenerated
     */
    private Long repairCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    public DeviceRepairEvaluations(Long code, Integer itemCode, String itemName, Integer levels, Long repairCode) {
        this.code = code;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.levels = levels;
        this.repairCode = repairCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_evaluations
     *
     * @mbggenerated
     */
    public DeviceRepairEvaluations() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_evaluations.code
     *
     * @return the value of device_repair_evaluations.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_evaluations.code
     *
     * @param code the value for device_repair_evaluations.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_evaluations.item_code
     *
     * @return the value of device_repair_evaluations.item_code
     *
     * @mbggenerated
     */
    public Integer getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_evaluations.item_code
     *
     * @param itemCode the value for device_repair_evaluations.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(Integer itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_evaluations.item_name
     *
     * @return the value of device_repair_evaluations.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_evaluations.item_name
     *
     * @param itemName the value for device_repair_evaluations.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_evaluations.levels
     *
     * @return the value of device_repair_evaluations.levels
     *
     * @mbggenerated
     */
    public Integer getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_evaluations.levels
     *
     * @param levels the value for device_repair_evaluations.levels
     *
     * @mbggenerated
     */
    public void setLevels(Integer levels) {
        this.levels = levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_repair_evaluations.repair_code
     *
     * @return the value of device_repair_evaluations.repair_code
     *
     * @mbggenerated
     */
    public Long getRepairCode() {
        return repairCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_repair_evaluations.repair_code
     *
     * @param repairCode the value for device_repair_evaluations.repair_code
     *
     * @mbggenerated
     */
    public void setRepairCode(Long repairCode) {
        this.repairCode = repairCode;
    }
}