package com.jinchi.app.domain;

public class DeviceSpotcheckRecordDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.record_code
     *
     * @mbggenerated
     */
    private Long recordCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.model_detail_code
     *
     * @mbggenerated
     */
    private Long modelDetailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.spotcheck_items
     *
     * @mbggenerated
     */
    private String spotcheckItems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.spotcheck_content
     *
     * @mbggenerated
     */
    private String spotcheckContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.main_values
     *
     * @mbggenerated
     */
    private Integer mainValues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_spotcheck_record_details.main_content
     *
     * @mbggenerated
     */
    private String mainContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_record_details
     *
     * @mbggenerated
     */
    public DeviceSpotcheckRecordDetails(Long code, Long recordCode, Long modelDetailCode, String spotcheckItems, String spotcheckContent, Integer mainValues, String mainContent) {
        this.code = code;
        this.recordCode = recordCode;
        this.modelDetailCode = modelDetailCode;
        this.spotcheckItems = spotcheckItems;
        this.spotcheckContent = spotcheckContent;
        this.mainValues = mainValues;
        this.mainContent = mainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_record_details
     *
     * @mbggenerated
     */
    public DeviceSpotcheckRecordDetails() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.code
     *
     * @return the value of device_spotcheck_record_details.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.code
     *
     * @param code the value for device_spotcheck_record_details.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.record_code
     *
     * @return the value of device_spotcheck_record_details.record_code
     *
     * @mbggenerated
     */
    public Long getRecordCode() {
        return recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.record_code
     *
     * @param recordCode the value for device_spotcheck_record_details.record_code
     *
     * @mbggenerated
     */
    public void setRecordCode(Long recordCode) {
        this.recordCode = recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.model_detail_code
     *
     * @return the value of device_spotcheck_record_details.model_detail_code
     *
     * @mbggenerated
     */
    public Long getModelDetailCode() {
        return modelDetailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.model_detail_code
     *
     * @param modelDetailCode the value for device_spotcheck_record_details.model_detail_code
     *
     * @mbggenerated
     */
    public void setModelDetailCode(Long modelDetailCode) {
        this.modelDetailCode = modelDetailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.spotcheck_items
     *
     * @return the value of device_spotcheck_record_details.spotcheck_items
     *
     * @mbggenerated
     */
    public String getSpotcheckItems() {
        return spotcheckItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.spotcheck_items
     *
     * @param spotcheckItems the value for device_spotcheck_record_details.spotcheck_items
     *
     * @mbggenerated
     */
    public void setSpotcheckItems(String spotcheckItems) {
        this.spotcheckItems = spotcheckItems == null ? null : spotcheckItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.spotcheck_content
     *
     * @return the value of device_spotcheck_record_details.spotcheck_content
     *
     * @mbggenerated
     */
    public String getSpotcheckContent() {
        return spotcheckContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.spotcheck_content
     *
     * @param spotcheckContent the value for device_spotcheck_record_details.spotcheck_content
     *
     * @mbggenerated
     */
    public void setSpotcheckContent(String spotcheckContent) {
        this.spotcheckContent = spotcheckContent == null ? null : spotcheckContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.main_values
     *
     * @return the value of device_spotcheck_record_details.main_values
     *
     * @mbggenerated
     */
    public Integer getMainValues() {
        return mainValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.main_values
     *
     * @param mainValues the value for device_spotcheck_record_details.main_values
     *
     * @mbggenerated
     */
    public void setMainValues(Integer mainValues) {
        this.mainValues = mainValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_spotcheck_record_details.main_content
     *
     * @return the value of device_spotcheck_record_details.main_content
     *
     * @mbggenerated
     */
    public String getMainContent() {
        return mainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_spotcheck_record_details.main_content
     *
     * @param mainContent the value for device_spotcheck_record_details.main_content
     *
     * @mbggenerated
     */
    public void setMainContent(String mainContent) {
        this.mainContent = mainContent == null ? null : mainContent.trim();
    }
}