package com.jinchi.app.mapper.fireMage;

import com.jinchi.app.domain.fireMage.FireMageNumberStream;
import com.jinchi.app.domain.fireMage.FireMageNumberStreamExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface FireMageNumberStreamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    int countByExample(FireMageNumberStreamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    int deleteByExample(FireMageNumberStreamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fire_mage_number_stream",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fire_mage_number_stream (value, description, ",
        "enable)",
        "values (#{value,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(FireMageNumberStream record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    int insertSelective(FireMageNumberStream record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    List<FireMageNumberStream> selectByExample(FireMageNumberStreamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, value, description, enable",
        "from fire_mage_number_stream",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    FireMageNumberStream selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FireMageNumberStream record, @Param("example") FireMageNumberStreamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FireMageNumberStream record, @Param("example") FireMageNumberStreamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FireMageNumberStream record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_stream
     *
     * @mbggenerated
     */
    @Update({
        "update fire_mage_number_stream",
        "set value = #{value,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FireMageNumberStream record);
}