package com.jinchi.app.mapper.fireMage;

import com.jinchi.app.domain.fireMage.FireMageOperationManual;
import com.jinchi.app.domain.fireMage.FireMageOperationManualExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface FireMageOperationManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    int countByExample(FireMageOperationManualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    int deleteByExample(FireMageOperationManualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fire_mage_operation_manual",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fire_mage_operation_manual (title, content)",
        "values (#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(FireMageOperationManual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    int insertSelective(FireMageOperationManual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    List<FireMageOperationManual> selectByExample(FireMageOperationManualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, title, content",
        "from fire_mage_operation_manual",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    FireMageOperationManual selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FireMageOperationManual record, @Param("example") FireMageOperationManualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FireMageOperationManual record, @Param("example") FireMageOperationManualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FireMageOperationManual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_operation_manual
     *
     * @mbggenerated
     */
    @Update({
        "update fire_mage_operation_manual",
        "set title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(FireMageOperationManual record);
}