package com.jinchi.app.mapper.fireMage;

import com.jinchi.app.domain.fireMage.FireMageNumberDay;
import com.jinchi.app.domain.fireMage.FireMageNumberDayExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface FireMageNumberDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    int countByExample(FireMageNumberDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    int deleteByExample(FireMageNumberDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fire_mage_number_day",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fire_mage_number_day (value, description, ",
        "enable)",
        "values (#{value,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(FireMageNumberDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    int insertSelective(FireMageNumberDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    List<FireMageNumberDay> selectByExample(FireMageNumberDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, value, description, enable",
        "from fire_mage_number_day",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    FireMageNumberDay selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FireMageNumberDay record, @Param("example") FireMageNumberDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FireMageNumberDay record, @Param("example") FireMageNumberDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FireMageNumberDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_day
     *
     * @mbggenerated
     */
    @Update({
        "update fire_mage_number_day",
        "set value = #{value,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FireMageNumberDay record);
}