package com.jinchi.app.mapper.fireMage;

import com.jinchi.app.domain.fireMage.FireMageNumberDev2;
import com.jinchi.app.domain.fireMage.FireMageNumberDev2Example;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface FireMageNumberDev2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    int countByExample(FireMageNumberDev2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    int deleteByExample(FireMageNumberDev2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fire_mage_number_dev2",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fire_mage_number_dev2 (value, description, ",
        "enable)",
        "values (#{value,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(FireMageNumberDev2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    int insertSelective(FireMageNumberDev2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    List<FireMageNumberDev2> selectByExample(FireMageNumberDev2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, value, description, enable",
        "from fire_mage_number_dev2",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    FireMageNumberDev2 selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FireMageNumberDev2 record, @Param("example") FireMageNumberDev2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FireMageNumberDev2 record, @Param("example") FireMageNumberDev2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FireMageNumberDev2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_dev2
     *
     * @mbggenerated
     */
    @Update({
        "update fire_mage_number_dev2",
        "set value = #{value,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FireMageNumberDev2 record);
}