package com.jinchi.common.mapper;

import com.jinchi.common.domain.AnodeGoodsInProcessStatisticByProcessTotals;
import com.jinchi.common.domain.AnodeGoodsInProcessStatisticByProcessTotalsExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface AnodeGoodsInProcessStatisticByProcessTotalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    int countByExample(AnodeGoodsInProcessStatisticByProcessTotalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    int deleteByExample(AnodeGoodsInProcessStatisticByProcessTotalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    @Delete({
        "delete from anode_goods_in_process_statistic_by_process_totals",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    @Insert({
        "insert into anode_goods_in_process_statistic_by_process_totals (statistic_code, periods, ",
        "line_code, type_code, ",
        "process_code, feedstock_totals, ",
        "consume_totals, balance_totals, ",
        "flag)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{periods,jdbcType=INTEGER}, ",
        "#{lineCode,jdbcType=INTEGER}, #{typeCode,jdbcType=INTEGER}, ",
        "#{processCode,jdbcType=INTEGER}, #{feedstockTotals,jdbcType=REAL}, ",
        "#{consumeTotals,jdbcType=REAL}, #{balanceTotals,jdbcType=REAL}, ",
        "#{flag,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AnodeGoodsInProcessStatisticByProcessTotals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    int insertSelective(AnodeGoodsInProcessStatisticByProcessTotals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    List<AnodeGoodsInProcessStatisticByProcessTotals> selectByExample(AnodeGoodsInProcessStatisticByProcessTotalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, periods, line_code, type_code, process_code, feedstock_totals, ",
        "consume_totals, balance_totals, flag",
        "from anode_goods_in_process_statistic_by_process_totals",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AnodeGoodsInProcessStatisticByProcessTotals selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnodeGoodsInProcessStatisticByProcessTotals record, @Param("example") AnodeGoodsInProcessStatisticByProcessTotalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnodeGoodsInProcessStatisticByProcessTotals record, @Param("example") AnodeGoodsInProcessStatisticByProcessTotalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnodeGoodsInProcessStatisticByProcessTotals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_process_totals
     *
     * @mbggenerated
     */
    @Update({
        "update anode_goods_in_process_statistic_by_process_totals",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "periods = #{periods,jdbcType=INTEGER},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "type_code = #{typeCode,jdbcType=INTEGER},",
          "process_code = #{processCode,jdbcType=INTEGER},",
          "feedstock_totals = #{feedstockTotals,jdbcType=REAL},",
          "consume_totals = #{consumeTotals,jdbcType=REAL},",
          "balance_totals = #{balanceTotals,jdbcType=REAL},",
          "flag = #{flag,jdbcType=BIT}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AnodeGoodsInProcessStatisticByProcessTotals record);
}