package com.jinchi.common.mapper;

import com.jinchi.common.domain.AnodeCostAccountingStatisticTotalsOnlineRawMaterial;
import com.jinchi.common.domain.AnodeCostAccountingStatisticTotalsOnlineRawMaterialExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface AnodeCostAccountingStatisticTotalsOnlineRawMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    int countByExample(AnodeCostAccountingStatisticTotalsOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    int deleteByExample(AnodeCostAccountingStatisticTotalsOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    @Delete({
        "delete from anode_cost_accounting_statistic_totals_online_raw_material",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    @Insert({
        "insert into anode_cost_accounting_statistic_totals_online_raw_material (statistic_code, material_code, ",
        "feedstock, balance)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{materialCode,jdbcType=INTEGER}, ",
        "#{feedstock,jdbcType=REAL}, #{balance,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AnodeCostAccountingStatisticTotalsOnlineRawMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    int insertSelective(AnodeCostAccountingStatisticTotalsOnlineRawMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    List<AnodeCostAccountingStatisticTotalsOnlineRawMaterial> selectByExample(AnodeCostAccountingStatisticTotalsOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, material_code, feedstock, balance",
        "from anode_cost_accounting_statistic_totals_online_raw_material",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AnodeCostAccountingStatisticTotalsOnlineRawMaterial selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnodeCostAccountingStatisticTotalsOnlineRawMaterial record, @Param("example") AnodeCostAccountingStatisticTotalsOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnodeCostAccountingStatisticTotalsOnlineRawMaterial record, @Param("example") AnodeCostAccountingStatisticTotalsOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnodeCostAccountingStatisticTotalsOnlineRawMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_totals_online_raw_material
     *
     * @mbggenerated
     */
    @Update({
        "update anode_cost_accounting_statistic_totals_online_raw_material",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "material_code = #{materialCode,jdbcType=INTEGER},",
          "feedstock = #{feedstock,jdbcType=REAL},",
          "balance = #{balance,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AnodeCostAccountingStatisticTotalsOnlineRawMaterial record);
}