package com.jinchi.common.mapper;

import com.jinchi.common.domain.AnodeGoodsInProcessStatisticByLineDetails;
import com.jinchi.common.domain.AnodeGoodsInProcessStatisticByLineDetailsExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface AnodeGoodsInProcessStatisticByLineDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    int countByExample(AnodeGoodsInProcessStatisticByLineDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    int deleteByExample(AnodeGoodsInProcessStatisticByLineDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    @Delete({
        "delete from anode_goods_in_process_statistic_by_line_details",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    @Insert({
        "insert into anode_goods_in_process_statistic_by_line_details (statistic_code, line_code, ",
        "type_code, periods, ",
        "raw_material, raw_material_balance, ",
        "first_process, second_proces, ",
        "product, period_code)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{lineCode,jdbcType=INTEGER}, ",
        "#{typeCode,jdbcType=INTEGER}, #{periods,jdbcType=INTEGER}, ",
        "#{rawMaterial,jdbcType=REAL}, #{rawMaterialBalance,jdbcType=REAL}, ",
        "#{firstProcess,jdbcType=REAL}, #{secondProces,jdbcType=REAL}, ",
        "#{product,jdbcType=REAL}, #{periodCode,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AnodeGoodsInProcessStatisticByLineDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    int insertSelective(AnodeGoodsInProcessStatisticByLineDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    List<AnodeGoodsInProcessStatisticByLineDetails> selectByExample(AnodeGoodsInProcessStatisticByLineDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, line_code, type_code, periods, raw_material, raw_material_balance, ",
        "first_process, second_proces, product, period_code",
        "from anode_goods_in_process_statistic_by_line_details",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AnodeGoodsInProcessStatisticByLineDetails selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnodeGoodsInProcessStatisticByLineDetails record, @Param("example") AnodeGoodsInProcessStatisticByLineDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnodeGoodsInProcessStatisticByLineDetails record, @Param("example") AnodeGoodsInProcessStatisticByLineDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnodeGoodsInProcessStatisticByLineDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_by_line_details
     *
     * @mbggenerated
     */
    @Update({
        "update anode_goods_in_process_statistic_by_line_details",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "type_code = #{typeCode,jdbcType=INTEGER},",
          "periods = #{periods,jdbcType=INTEGER},",
          "raw_material = #{rawMaterial,jdbcType=REAL},",
          "raw_material_balance = #{rawMaterialBalance,jdbcType=REAL},",
          "first_process = #{firstProcess,jdbcType=REAL},",
          "second_proces = #{secondProces,jdbcType=REAL},",
          "product = #{product,jdbcType=REAL},",
          "period_code = #{periodCode,jdbcType=INTEGER}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AnodeGoodsInProcessStatisticByLineDetails record);

    List selectBySQL(@Param("sql") String sql);
}