package com.jinchi.common.mapper;

import com.jinchi.common.domain.AnodeGoodsInProcessStatisticSecondSintering;
import com.jinchi.common.domain.AnodeGoodsInProcessStatisticSecondSinteringExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface AnodeGoodsInProcessStatisticSecondSinteringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    int countByExample(AnodeGoodsInProcessStatisticSecondSinteringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    int deleteByExample(AnodeGoodsInProcessStatisticSecondSinteringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    @Delete({
        "delete from anode_goods_in_process_statistic_second_sintering",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    @Insert({
        "insert into anode_goods_in_process_statistic_second_sintering (statistic_code, material_code, ",
        "line_code, type_code, ",
        "process_code, feedstock, ",
        "consume, balance, into_furnace_num, ",
        "out_furnace_num)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{materialCode,jdbcType=INTEGER}, ",
        "#{lineCode,jdbcType=INTEGER}, #{typeCode,jdbcType=INTEGER}, ",
        "#{processCode,jdbcType=INTEGER}, #{feedstock,jdbcType=REAL}, ",
        "#{consume,jdbcType=REAL}, #{balance,jdbcType=REAL}, #{intoFurnaceNum,jdbcType=INTEGER}, ",
        "#{outFurnaceNum,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AnodeGoodsInProcessStatisticSecondSintering record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    int insertSelective(AnodeGoodsInProcessStatisticSecondSintering record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    List<AnodeGoodsInProcessStatisticSecondSintering> selectByExample(AnodeGoodsInProcessStatisticSecondSinteringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, material_code, line_code, type_code, process_code, feedstock, ",
        "consume, balance, into_furnace_num, out_furnace_num",
        "from anode_goods_in_process_statistic_second_sintering",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AnodeGoodsInProcessStatisticSecondSintering selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnodeGoodsInProcessStatisticSecondSintering record, @Param("example") AnodeGoodsInProcessStatisticSecondSinteringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnodeGoodsInProcessStatisticSecondSintering record, @Param("example") AnodeGoodsInProcessStatisticSecondSinteringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnodeGoodsInProcessStatisticSecondSintering record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_second_sintering
     *
     * @mbggenerated
     */
    @Update({
        "update anode_goods_in_process_statistic_second_sintering",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "material_code = #{materialCode,jdbcType=INTEGER},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "type_code = #{typeCode,jdbcType=INTEGER},",
          "process_code = #{processCode,jdbcType=INTEGER},",
          "feedstock = #{feedstock,jdbcType=REAL},",
          "consume = #{consume,jdbcType=REAL},",
          "balance = #{balance,jdbcType=REAL},",
          "into_furnace_num = #{intoFurnaceNum,jdbcType=INTEGER},",
          "out_furnace_num = #{outFurnaceNum,jdbcType=INTEGER}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AnodeGoodsInProcessStatisticSecondSintering record);
}