package com.jinchi.common.mapper;

import com.jinchi.common.domain.AnodeCostAccountingStatisticByLineOnlineRawMaterial;
import com.jinchi.common.domain.AnodeCostAccountingStatisticByLineOnlineRawMaterialExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface AnodeCostAccountingStatisticByLineOnlineRawMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    int countByExample(AnodeCostAccountingStatisticByLineOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    int deleteByExample(AnodeCostAccountingStatisticByLineOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    @Delete({
        "delete from anode_cost_accounting_statistic_by_line_online_raw_material",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    @Insert({
        "insert into anode_cost_accounting_statistic_by_line_online_raw_material (statistic_code, material_code, ",
        "line_code, type_code, ",
        "feedstock, balance)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{materialCode,jdbcType=INTEGER}, ",
        "#{lineCode,jdbcType=INTEGER}, #{typeCode,jdbcType=INTEGER}, ",
        "#{feedstock,jdbcType=REAL}, #{balance,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AnodeCostAccountingStatisticByLineOnlineRawMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    int insertSelective(AnodeCostAccountingStatisticByLineOnlineRawMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    List<AnodeCostAccountingStatisticByLineOnlineRawMaterial> selectByExample(AnodeCostAccountingStatisticByLineOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, material_code, line_code, type_code, feedstock, balance",
        "from anode_cost_accounting_statistic_by_line_online_raw_material",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AnodeCostAccountingStatisticByLineOnlineRawMaterial selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnodeCostAccountingStatisticByLineOnlineRawMaterial record, @Param("example") AnodeCostAccountingStatisticByLineOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnodeCostAccountingStatisticByLineOnlineRawMaterial record, @Param("example") AnodeCostAccountingStatisticByLineOnlineRawMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnodeCostAccountingStatisticByLineOnlineRawMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_cost_accounting_statistic_by_line_online_raw_material
     *
     * @mbggenerated
     */
    @Update({
        "update anode_cost_accounting_statistic_by_line_online_raw_material",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "material_code = #{materialCode,jdbcType=INTEGER},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "type_code = #{typeCode,jdbcType=INTEGER},",
          "feedstock = #{feedstock,jdbcType=REAL},",
          "balance = #{balance,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AnodeCostAccountingStatisticByLineOnlineRawMaterial record);
}