package com.jinchi.common.mapper;

import com.jinchi.common.domain.AnodeGoodsInProcessStatisticPremixTemporaryStorage;
import com.jinchi.common.domain.AnodeGoodsInProcessStatisticPremixTemporaryStorageExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface AnodeGoodsInProcessStatisticPremixTemporaryStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    int countByExample(AnodeGoodsInProcessStatisticPremixTemporaryStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    int deleteByExample(AnodeGoodsInProcessStatisticPremixTemporaryStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    @Delete({
        "delete from anode_goods_in_process_statistic_premix_temporary_storage",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    @Insert({
        "insert into anode_goods_in_process_statistic_premix_temporary_storage (statistic_code, material_code, ",
        "line_code, type_code, ",
        "process_code, feedstock, ",
        "consume, balance)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{materialCode,jdbcType=INTEGER}, ",
        "#{lineCode,jdbcType=INTEGER}, #{typeCode,jdbcType=INTEGER}, ",
        "#{processCode,jdbcType=INTEGER}, #{feedstock,jdbcType=REAL}, ",
        "#{consume,jdbcType=REAL}, #{balance,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AnodeGoodsInProcessStatisticPremixTemporaryStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    int insertSelective(AnodeGoodsInProcessStatisticPremixTemporaryStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    List<AnodeGoodsInProcessStatisticPremixTemporaryStorage> selectByExample(AnodeGoodsInProcessStatisticPremixTemporaryStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, material_code, line_code, type_code, process_code, feedstock, ",
        "consume, balance",
        "from anode_goods_in_process_statistic_premix_temporary_storage",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AnodeGoodsInProcessStatisticPremixTemporaryStorage selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnodeGoodsInProcessStatisticPremixTemporaryStorage record, @Param("example") AnodeGoodsInProcessStatisticPremixTemporaryStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnodeGoodsInProcessStatisticPremixTemporaryStorage record, @Param("example") AnodeGoodsInProcessStatisticPremixTemporaryStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnodeGoodsInProcessStatisticPremixTemporaryStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_premix_temporary_storage
     *
     * @mbggenerated
     */
    @Update({
        "update anode_goods_in_process_statistic_premix_temporary_storage",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "material_code = #{materialCode,jdbcType=INTEGER},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "type_code = #{typeCode,jdbcType=INTEGER},",
          "process_code = #{processCode,jdbcType=INTEGER},",
          "feedstock = #{feedstock,jdbcType=REAL},",
          "consume = #{consume,jdbcType=REAL},",
          "balance = #{balance,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AnodeGoodsInProcessStatisticPremixTemporaryStorage record);
}