package com.jinchi.common.mapper;

import com.jinchi.common.domain.AuxiliaryMaterialsStatisticDataList;
import com.jinchi.common.domain.AuxiliaryMaterialsStatisticDataListExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface AuxiliaryMaterialsStatisticDataListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    int countByExample(AuxiliaryMaterialsStatisticDataListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    int deleteByExample(AuxiliaryMaterialsStatisticDataListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    @Delete({
        "delete from auxiliary_materials_statistic_data_list",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    @Insert({
        "insert into auxiliary_materials_statistic_data_list (statistic_code, periods, ",
        "process_code, totals, ",
        "ammonia_value, alkali_value)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{periods,jdbcType=INTEGER}, ",
        "#{processCode,jdbcType=INTEGER}, #{totals,jdbcType=REAL}, ",
        "#{ammoniaValue,jdbcType=REAL}, #{alkaliValue,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(AuxiliaryMaterialsStatisticDataList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    int insertSelective(AuxiliaryMaterialsStatisticDataList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    List<AuxiliaryMaterialsStatisticDataList> selectByExample(AuxiliaryMaterialsStatisticDataListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, periods, process_code, totals, ammonia_value, alkali_value",
        "from auxiliary_materials_statistic_data_list",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AuxiliaryMaterialsStatisticDataList selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuxiliaryMaterialsStatisticDataList record, @Param("example") AuxiliaryMaterialsStatisticDataListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuxiliaryMaterialsStatisticDataList record, @Param("example") AuxiliaryMaterialsStatisticDataListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuxiliaryMaterialsStatisticDataList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_data_list
     *
     * @mbggenerated
     */
    @Update({
        "update auxiliary_materials_statistic_data_list",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "periods = #{periods,jdbcType=INTEGER},",
          "process_code = #{processCode,jdbcType=INTEGER},",
          "totals = #{totals,jdbcType=REAL},",
          "ammonia_value = #{ammoniaValue,jdbcType=REAL},",
          "alkali_value = #{alkaliValue,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AuxiliaryMaterialsStatisticDataList record);
}