package com.jinchi.common.mapper;


import com.jinchi.common.domain.BasicInfoAnodeProductionType;
import com.jinchi.common.domain.BasicInfoAnodeProductionTypeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoAnodeProductionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int countByExample(BasicInfoAnodeProductionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int deleteByExample(BasicInfoAnodeProductionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int insert(BasicInfoAnodeProductionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int insertSelective(BasicInfoAnodeProductionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    List<BasicInfoAnodeProductionType> selectByExample(BasicInfoAnodeProductionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    BasicInfoAnodeProductionType selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasicInfoAnodeProductionType record, @Param("example") BasicInfoAnodeProductionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int updateByExample(@Param("record") BasicInfoAnodeProductionType record, @Param("example") BasicInfoAnodeProductionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int updateByPrimaryKeySelective(BasicInfoAnodeProductionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_production_type
     *
     * @mbggenerated Sun Mar 29 17:07:39 CST 2020
     */
    int updateByPrimaryKey(BasicInfoAnodeProductionType record);
}