package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoRawmaterialLineWeight;
import com.jinchi.common.domain.BasicInfoRawmaterialLineWeightExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoRawmaterialLineWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoRawmaterialLineWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoRawmaterialLineWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_rawmaterial_line_weight",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_rawmaterial_line_weight (material_code, line_code, ",
        "weight_value)",
        "values (#{materialCode,jdbcType=INTEGER}, #{lineCode,jdbcType=INTEGER}, ",
        "#{weightValue,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(BasicInfoRawmaterialLineWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoRawmaterialLineWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    List<BasicInfoRawmaterialLineWeight> selectByExample(BasicInfoRawmaterialLineWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, material_code, line_code, weight_value",
        "from basic_info_rawmaterial_line_weight",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoRawmaterialLineWeight selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoRawmaterialLineWeight record, @Param("example") BasicInfoRawmaterialLineWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoRawmaterialLineWeight record, @Param("example") BasicInfoRawmaterialLineWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoRawmaterialLineWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_rawmaterial_line_weight
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_rawmaterial_line_weight",
        "set material_code = #{materialCode,jdbcType=INTEGER},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "weight_value = #{weightValue,jdbcType=REAL}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoRawmaterialLineWeight record);
}