package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoMaterialType;
import com.jinchi.common.domain.BasicInfoMaterialTypeExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoMaterialTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoMaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoMaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_material_type",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_material_type (material_type_name, data_type)",
        "values (#{materialTypeName,jdbcType=VARCHAR}, #{dataType,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(BasicInfoMaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoMaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    List<BasicInfoMaterialType> selectByExample(BasicInfoMaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, material_type_name, data_type",
        "from basic_info_material_type",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoMaterialType selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoMaterialType record, @Param("example") BasicInfoMaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoMaterialType record, @Param("example") BasicInfoMaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoMaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_material_type
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_material_type",
        "set material_type_name = #{materialTypeName,jdbcType=VARCHAR},",
          "data_type = #{dataType,jdbcType=TINYINT}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoMaterialType record);
}