package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoVgaPoint;
import com.jinchi.common.domain.BasicInfoVgaPointExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoVgaPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoVgaPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoVgaPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_VGA_point",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_VGA_point (code, vga_name)",
        "values (#{code,jdbcType=INTEGER}, #{vgaName,jdbcType=VARCHAR})"
    })
    int insert(BasicInfoVgaPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoVgaPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    List<BasicInfoVgaPoint> selectByExample(BasicInfoVgaPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, vga_name",
        "from basic_info_VGA_point",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoVgaPoint selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoVgaPoint record, @Param("example") BasicInfoVgaPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoVgaPoint record, @Param("example") BasicInfoVgaPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoVgaPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_VGA_point
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_VGA_point",
        "set vga_name = #{vgaName,jdbcType=VARCHAR}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoVgaPoint record);
}