package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoPrecursorPeriod;
import com.jinchi.common.domain.BasicInfoPrecursorPeriodExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoPrecursorPeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoPrecursorPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoPrecursorPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_precursor_period",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_precursor_period (code, name, ",
        "start_time, length)",
        "values (#{code,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{startTime,jdbcType=TIMESTAMP}, #{length,jdbcType=INTEGER})"
    })
    int insert(BasicInfoPrecursorPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoPrecursorPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    List<BasicInfoPrecursorPeriod> selectByExample(BasicInfoPrecursorPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, name, start_time, length",
        "from basic_info_precursor_period",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoPrecursorPeriod selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoPrecursorPeriod record, @Param("example") BasicInfoPrecursorPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoPrecursorPeriod record, @Param("example") BasicInfoPrecursorPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoPrecursorPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_period
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_precursor_period",
        "set name = #{name,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "length = #{length,jdbcType=INTEGER}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoPrecursorPeriod record);
}