package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoAnodePeriod;
import com.jinchi.common.domain.BasicInfoAnodePeriodExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface BasicInfoAnodePeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoAnodePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoAnodePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_anode_period",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_anode_period (name, start_time, ",
        "length)",
        "values (#{name,jdbcType=VARCHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{length,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(BasicInfoAnodePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoAnodePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    List<BasicInfoAnodePeriod> selectByExample(BasicInfoAnodePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, name, start_time, length",
        "from basic_info_anode_period",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoAnodePeriod selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoAnodePeriod record, @Param("example") BasicInfoAnodePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoAnodePeriod record, @Param("example") BasicInfoAnodePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoAnodePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_period
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_anode_period",
        "set name = #{name,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "length = #{length,jdbcType=REAL}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoAnodePeriod record);
}