package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoAnodePlcAddress;
import com.jinchi.common.domain.BasicInfoAnodePlcAddressExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoAnodePlcAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoAnodePlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoAnodePlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_anode_PLC_address",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_anode_PLC_address (plc_address, description)",
        "values (#{plcAddress,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(BasicInfoAnodePlcAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoAnodePlcAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    List<BasicInfoAnodePlcAddress> selectByExample(BasicInfoAnodePlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, plc_address, description",
        "from basic_info_anode_PLC_address",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoAnodePlcAddress selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoAnodePlcAddress record, @Param("example") BasicInfoAnodePlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoAnodePlcAddress record, @Param("example") BasicInfoAnodePlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoAnodePlcAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_PLC_address
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_anode_PLC_address",
        "set plc_address = #{plcAddress,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoAnodePlcAddress record);
}