package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoUserDeviceDeptMap;
import com.jinchi.common.domain.BasicInfoUserDeviceDeptMapExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface BasicInfoUserDeviceDeptMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoUserDeviceDeptMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoUserDeviceDeptMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_user_device_dept_map (code, auth_code, ",
        "dept_code)",
        "values (#{code,jdbcType=INTEGER}, #{authCode,jdbcType=INTEGER}, ",
        "#{deptCode,jdbcType=INTEGER})"
    })
    int insert(BasicInfoUserDeviceDeptMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoUserDeviceDeptMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    List<BasicInfoUserDeviceDeptMap> selectByExample(BasicInfoUserDeviceDeptMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoUserDeviceDeptMap record, @Param("example") BasicInfoUserDeviceDeptMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_user_device_dept_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoUserDeviceDeptMap record, @Param("example") BasicInfoUserDeviceDeptMapExample example);

    List<BasicInfoUserDeviceDeptMap> selectByCondition(@Param("sql")String sql);

    Integer count(@Param("sql") String sql);
}