package com.jinchi.common.mapper;


import com.jinchi.common.domain.BasicInfoDept;
import com.jinchi.common.domain.BasicInfoDeptExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface BasicInfoDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_dept (code, name, ",
        "parent_code)",
        "values (#{code,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{parentCode,jdbcType=INTEGER})"
    })
    int insert(BasicInfoDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    List<BasicInfoDept> selectByExample(BasicInfoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoDept record, @Param("example") BasicInfoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_dept
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoDept record, @Param("example") BasicInfoDeptExample example);
}