package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoPrecursorPlcAddress;
import com.jinchi.common.domain.BasicInfoPrecursorPlcAddressExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface BasicInfoPrecursorPlcAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoPrecursorPlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoPrecursorPlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_precursor_PLC_address",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_precursor_PLC_address (code, address, ",
        "description)",
        "values (#{code,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    int insert(BasicInfoPrecursorPlcAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoPrecursorPlcAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    List<BasicInfoPrecursorPlcAddress> selectByExample(BasicInfoPrecursorPlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, address, description",
        "from basic_info_precursor_PLC_address",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoPrecursorPlcAddress selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoPrecursorPlcAddress record, @Param("example") BasicInfoPrecursorPlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoPrecursorPlcAddress record, @Param("example") BasicInfoPrecursorPlcAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoPrecursorPlcAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_precursor_PLC_address
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_precursor_PLC_address",
        "set address = #{address,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoPrecursorPlcAddress record);
}