package com.jinchi.common.mapper;

import com.jinchi.common.domain.BasicInfoAnodeMaterialPlcMap;
import com.jinchi.common.domain.BasicInfoAnodeMaterialPlcMapExample;
import com.jinchi.common.dto.AnodeMatPlcMapDTO;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface BasicInfoAnodeMaterialPlcMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    int countByExample(BasicInfoAnodeMaterialPlcMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    int deleteByExample(BasicInfoAnodeMaterialPlcMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    @Delete({
        "delete from basic_info_anode_material_PLC_map",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    @Insert({
        "insert into basic_info_anode_material_PLC_map (line_code, process_code, ",
        "material_code, material_att, ",
        "plc_code)",
        "values (#{lineCode,jdbcType=INTEGER}, #{processCode,jdbcType=INTEGER}, ",
        "#{materialCode,jdbcType=INTEGER}, #{materialAtt,jdbcType=VARCHAR}, ",
        "#{plcCode,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(BasicInfoAnodeMaterialPlcMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    int insertSelective(BasicInfoAnodeMaterialPlcMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    List<BasicInfoAnodeMaterialPlcMap> selectByExample(BasicInfoAnodeMaterialPlcMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, line_code, process_code, material_code, material_att, plc_code",
        "from basic_info_anode_material_PLC_map",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BasicInfoAnodeMaterialPlcMap selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasicInfoAnodeMaterialPlcMap record, @Param("example") BasicInfoAnodeMaterialPlcMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasicInfoAnodeMaterialPlcMap record, @Param("example") BasicInfoAnodeMaterialPlcMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicInfoAnodeMaterialPlcMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_material_PLC_map
     *
     * @mbggenerated
     */
    @Update({
        "update basic_info_anode_material_PLC_map",
        "set line_code = #{lineCode,jdbcType=INTEGER},",
          "process_code = #{processCode,jdbcType=INTEGER},",
          "material_code = #{materialCode,jdbcType=INTEGER},",
          "material_att = #{materialAtt,jdbcType=VARCHAR},",
          "plc_code = #{plcCode,jdbcType=INTEGER}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicInfoAnodeMaterialPlcMap record);

    List<AnodeMatPlcMapDTO> selectByCondition(@Param("condition") String condition);

    AnodeMatPlcMapDTO selectById(@Param("id") Integer id);
}