package com.jinchi.common.mapper;

import com.jinchi.common.domain.CostAccountingStatisticHead;
import com.jinchi.common.domain.CostAccountingStatisticHeadExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface CostAccountingStatisticHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    int countByExample(CostAccountingStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    int deleteByExample(CostAccountingStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    @Delete({
        "delete from cost_accounting_statistic_head",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    @Insert({
        "insert into cost_accounting_statistic_head (period_code, periods, ",
        "start_time, end_time, ",
        "flag)",
        "values (#{periodCode,jdbcType=INTEGER}, #{periods,jdbcType=INTEGER}, ",
        "#{startTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{flag,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(CostAccountingStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    int insertSelective(CostAccountingStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    List<CostAccountingStatisticHead> selectByExample(CostAccountingStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, period_code, periods, start_time, end_time, flag",
        "from cost_accounting_statistic_head",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    CostAccountingStatisticHead selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CostAccountingStatisticHead record, @Param("example") CostAccountingStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CostAccountingStatisticHead record, @Param("example") CostAccountingStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CostAccountingStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_accounting_statistic_head
     *
     * @mbggenerated
     */
    @Update({
        "update cost_accounting_statistic_head",
        "set period_code = #{periodCode,jdbcType=INTEGER},",
          "periods = #{periods,jdbcType=INTEGER},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "flag = #{flag,jdbcType=BIT}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CostAccountingStatisticHead record);
}