package com.jinchi.common.mapper;

import com.jinchi.common.domain.DeviceSpotcheckModelsDetails;
import com.jinchi.common.domain.DeviceSpotcheckModelsDetailsExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DeviceSpotcheckModelsDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    int countByExample(DeviceSpotcheckModelsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceSpotcheckModelsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_spotcheck_models_details (code, model_code, ",
        "spotcheck_items, spotcheck_content, ",
        "spotcheck_period, spotcheck_address)",
        "values (#{code,jdbcType=BIGINT}, #{modelCode,jdbcType=BIGINT}, ",
        "#{spotcheckItems,jdbcType=VARCHAR}, #{spotcheckContent,jdbcType=VARCHAR}, ",
        "#{spotcheckPeriod,jdbcType=VARCHAR}, #{spotcheckAddress,jdbcType=VARCHAR})"
    })
    int insert(DeviceSpotcheckModelsDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    int insertSelective(DeviceSpotcheckModelsDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    List<DeviceSpotcheckModelsDetails> selectByExample(DeviceSpotcheckModelsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceSpotcheckModelsDetails record, @Param("example") DeviceSpotcheckModelsDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_spotcheck_models_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceSpotcheckModelsDetails record, @Param("example") DeviceSpotcheckModelsDetailsExample example);
}