package com.jinchi.common.mapper;

import com.jinchi.common.domain.DeviceRepairApplication;
import com.jinchi.common.domain.DeviceRepairApplicationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Mapper
@Component
public interface DeviceRepairApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int countByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int deleteByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int insert(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int insertSelective(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    List<DeviceRepairApplication> selectByExample(DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    DeviceRepairApplication selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceRepairApplication record, @Param("example") DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int updateByExample(@Param("record") DeviceRepairApplication record, @Param("example") DeviceRepairApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceRepairApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_repair_application
     *
     * @mbggenerated Mon Mar 30 15:10:53 CST 2020
     */
    int updateByPrimaryKey(DeviceRepairApplication record);

    List<DeviceRepairApplication> selectBycondition(@Param("sql") String sql);

    List<Map<String, Object>> getDoneJson(@Param("repairStatus") Integer repairStatus, @Param("deptCode") Integer secondDeptCode, @Param("condition") String condition, @Param("startTime") String startTime, @Param("endTime") String endTime);

    Integer count(@Param("sql") String sql);
}