package com.jinchi.common.mapper;

import com.jinchi.common.domain.DeviceMainAttributelist;
import com.jinchi.common.domain.DeviceMainAttributelistExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DeviceMainAttributelistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    int countByExample(DeviceMainAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceMainAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_main_attributelist (code, name, ",
        "att_value, main_code)",
        "values (#{code,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{attValue,jdbcType=VARCHAR}, #{mainCode,jdbcType=BIGINT})"
    })
    int insert(DeviceMainAttributelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    int insertSelective(DeviceMainAttributelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    List<DeviceMainAttributelist> selectByExample(DeviceMainAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceMainAttributelist record, @Param("example") DeviceMainAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_main_attributelist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceMainAttributelist record, @Param("example") DeviceMainAttributelistExample example);
}