package com.jinchi.common.mapper;

import com.jinchi.common.domain.DeviceMaintenancePlansDetails;
import com.jinchi.common.domain.DeviceMaintenancePlansDetailsExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DeviceMaintenancePlansDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    int countByExample(DeviceMaintenancePlansDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceMaintenancePlansDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_maintenance_plans_details (code, plan_code, ",
        "maintenance_items, maintenance_content, ",
        "opt_type, items_code)",
        "values (#{code,jdbcType=INTEGER}, #{planCode,jdbcType=BIGINT}, ",
        "#{maintenanceItems,jdbcType=VARCHAR}, #{maintenanceContent,jdbcType=VARCHAR}, ",
        "#{optType,jdbcType=INTEGER}, #{itemsCode,jdbcType=BIGINT})"
    })
    int insert(DeviceMaintenancePlansDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    int insertSelective(DeviceMaintenancePlansDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    List<DeviceMaintenancePlansDetails> selectByExample(DeviceMaintenancePlansDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceMaintenancePlansDetails record, @Param("example") DeviceMaintenancePlansDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintenance_plans_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceMaintenancePlansDetails record, @Param("example") DeviceMaintenancePlansDetailsExample example);
}