package com.jinchi.common.mapper;

import com.jinchi.common.domain.DevicePatrolModelsLocationDetails;
import com.jinchi.common.domain.DevicePatrolModelsLocationDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface DevicePatrolModelsLocationDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    int countByExample(DevicePatrolModelsLocationDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    int deleteByExample(DevicePatrolModelsLocationDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_patrol_models_location_details (code, model_code, ",
        "location_code, location_name)",
        "values (#{code,jdbcType=BIGINT}, #{modelCode,jdbcType=BIGINT}, ",
        "#{locationCode,jdbcType=INTEGER}, #{locationName,jdbcType=VARCHAR})"
    })
    int insert(DevicePatrolModelsLocationDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    int insertSelective(DevicePatrolModelsLocationDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    List<DevicePatrolModelsLocationDetails> selectByExample(DevicePatrolModelsLocationDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DevicePatrolModelsLocationDetails record, @Param("example") DevicePatrolModelsLocationDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_location_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DevicePatrolModelsLocationDetails record, @Param("example") DevicePatrolModelsLocationDetailsExample example);
}