package com.jinchi.common.mapper;

import com.jinchi.common.domain.DeviceUnitAttributelist;
import com.jinchi.common.domain.DeviceUnitAttributelistExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;


@Mapper
@Component
public interface DeviceUnitAttributelistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    int countByExample(DeviceUnitAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceUnitAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_unit_attributelist (code, name, ",
        "att_values, unit_code)",
        "values (#{code,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{attValues,jdbcType=VARCHAR}, #{unitCode,jdbcType=BIGINT})"
    })
    int insert(DeviceUnitAttributelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    int insertSelective(DeviceUnitAttributelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    List<DeviceUnitAttributelist> selectByExample(DeviceUnitAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceUnitAttributelist record, @Param("example") DeviceUnitAttributelistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_attributelist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceUnitAttributelist record, @Param("example") DeviceUnitAttributelistExample example);
}