package com.jinchi.common.mapper;

import com.jinchi.common.domain.DevicePatrolModelsItemDetails;
import com.jinchi.common.domain.DevicePatrolModelsItemDetailsExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DevicePatrolModelsItemDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    int countByExample(DevicePatrolModelsItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    int deleteByExample(DevicePatrolModelsItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    @Insert({
        "insert into device_patrol_models_item_details (code, model_code, ",
        "patrol_item, patrol_content)",
        "values (#{code,jdbcType=BIGINT}, #{modelCode,jdbcType=BIGINT}, ",
        "#{patrolItem,jdbcType=VARCHAR}, #{patrolContent,jdbcType=VARCHAR})"
    })
    int insert(DevicePatrolModelsItemDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    int insertSelective(DevicePatrolModelsItemDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    List<DevicePatrolModelsItemDetails> selectByExample(DevicePatrolModelsItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DevicePatrolModelsItemDetails record, @Param("example") DevicePatrolModelsItemDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_patrol_models_item_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DevicePatrolModelsItemDetails record, @Param("example") DevicePatrolModelsItemDetailsExample example);
}