package com.jinchi.common.mapper;

import com.jinchi.common.domain.FireMageNumberYear;
import com.jinchi.common.domain.FireMageNumberYearExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface FireMageNumberYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    int countByExample(FireMageNumberYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    int deleteByExample(FireMageNumberYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fire_mage_number_year",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fire_mage_number_year (value, description, ",
        "enable)",
        "values (#{value,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(FireMageNumberYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    int insertSelective(FireMageNumberYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    List<FireMageNumberYear> selectByExample(FireMageNumberYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, value, description, enable",
        "from fire_mage_number_year",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    FireMageNumberYear selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FireMageNumberYear record, @Param("example") FireMageNumberYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FireMageNumberYear record, @Param("example") FireMageNumberYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FireMageNumberYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_year
     *
     * @mbggenerated
     */
    @Update({
        "update fire_mage_number_year",
        "set value = #{value,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FireMageNumberYear record);
}