package com.jinchi.common.mapper;

import com.jinchi.common.domain.FireMageNumberProcess;
import com.jinchi.common.domain.FireMageNumberProcessExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface FireMageNumberProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    int countByExample(FireMageNumberProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    int deleteByExample(FireMageNumberProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fire_mage_number_process",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fire_mage_number_process (value, description, ",
        "enable)",
        "values (#{value,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Integer.class)
    int insert(FireMageNumberProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    int insertSelective(FireMageNumberProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    List<FireMageNumberProcess> selectByExample(FireMageNumberProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, value, description, enable",
        "from fire_mage_number_process",
        "where code = #{code,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    FireMageNumberProcess selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FireMageNumberProcess record, @Param("example") FireMageNumberProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FireMageNumberProcess record, @Param("example") FireMageNumberProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FireMageNumberProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_number_process
     *
     * @mbggenerated
     */
    @Update({
        "update fire_mage_number_process",
        "set value = #{value,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT}",
        "where code = #{code,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FireMageNumberProcess record);
}