package com.jinchi.common.mapper;

import com.jinchi.common.domain.GoodsInProcessStatisticByLineDetail;
import com.jinchi.common.domain.GoodsInProcessStatisticByLineDetailExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface GoodsInProcessStatisticByLineDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    int countByExample(GoodsInProcessStatisticByLineDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsInProcessStatisticByLineDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    @Delete({
        "delete from goods_in_process_statistic_by_line_detail",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into goods_in_process_statistic_by_line_detail (code, statistic_code, ",
        "line_name, line_code, ",
        "totals, Ni_value, Co_value, ",
        "Mn_value)",
        "values (#{code,jdbcType=BIGINT}, #{statisticCode,jdbcType=BIGINT}, ",
        "#{lineName,jdbcType=INTEGER}, #{lineCode,jdbcType=INTEGER}, ",
        "#{totals,jdbcType=REAL}, #{niValue,jdbcType=REAL}, #{coValue,jdbcType=REAL}, ",
        "#{mnValue,jdbcType=REAL})"
    })
    int insert(GoodsInProcessStatisticByLineDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    int insertSelective(GoodsInProcessStatisticByLineDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    List<GoodsInProcessStatisticByLineDetail> selectByExample(GoodsInProcessStatisticByLineDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, line_name, line_code, totals, Ni_value, Co_value, Mn_value",
        "from goods_in_process_statistic_by_line_detail",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    GoodsInProcessStatisticByLineDetail selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsInProcessStatisticByLineDetail record, @Param("example") GoodsInProcessStatisticByLineDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsInProcessStatisticByLineDetail record, @Param("example") GoodsInProcessStatisticByLineDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsInProcessStatisticByLineDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_line_detail
     *
     * @mbggenerated
     */
    @Update({
        "update goods_in_process_statistic_by_line_detail",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "line_name = #{lineName,jdbcType=INTEGER},",
          "line_code = #{lineCode,jdbcType=INTEGER},",
          "totals = #{totals,jdbcType=REAL},",
          "Ni_value = #{niValue,jdbcType=REAL},",
          "Co_value = #{coValue,jdbcType=REAL},",
          "Mn_value = #{mnValue,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsInProcessStatisticByLineDetail record);
}