package com.jinchi.common.mapper;

import com.jinchi.common.domain.GoodsInProcessStatisticByProcessTotal;
import com.jinchi.common.domain.GoodsInProcessStatisticByProcessTotalExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface GoodsInProcessStatisticByProcessTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    int countByExample(GoodsInProcessStatisticByProcessTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsInProcessStatisticByProcessTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    @Delete({
        "delete from goods_in_process_statistic_by_process_total",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    @Insert({
        "insert into goods_in_process_statistic_by_process_total (code, statistic_code, ",
        "line_name, totals, Ni_value, ",
        "Co_value, Mn_value)",
        "values (#{code,jdbcType=BIGINT}, #{statisticCode,jdbcType=BIGINT}, ",
        "#{lineName,jdbcType=INTEGER}, #{totals,jdbcType=REAL}, #{niValue,jdbcType=REAL}, ",
        "#{coValue,jdbcType=REAL}, #{mnValue,jdbcType=REAL})"
    })
    int insert(GoodsInProcessStatisticByProcessTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    int insertSelective(GoodsInProcessStatisticByProcessTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    List<GoodsInProcessStatisticByProcessTotal> selectByExample(GoodsInProcessStatisticByProcessTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, line_name, totals, Ni_value, Co_value, Mn_value",
        "from goods_in_process_statistic_by_process_total",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    GoodsInProcessStatisticByProcessTotal selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsInProcessStatisticByProcessTotal record, @Param("example") GoodsInProcessStatisticByProcessTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsInProcessStatisticByProcessTotal record, @Param("example") GoodsInProcessStatisticByProcessTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsInProcessStatisticByProcessTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_by_process_total
     *
     * @mbggenerated
     */
    @Update({
        "update goods_in_process_statistic_by_process_total",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "line_name = #{lineName,jdbcType=INTEGER},",
          "totals = #{totals,jdbcType=REAL},",
          "Ni_value = #{niValue,jdbcType=REAL},",
          "Co_value = #{coValue,jdbcType=REAL},",
          "Mn_value = #{mnValue,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsInProcessStatisticByProcessTotal record);
}