package com.jinchi.common.mapper;

import com.jinchi.common.domain.MaterialDeliveryStatisticCobaltSulfate;
import com.jinchi.common.domain.MaterialDeliveryStatisticCobaltSulfateExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface MaterialDeliveryStatisticCobaltSulfateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    int countByExample(MaterialDeliveryStatisticCobaltSulfateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    int deleteByExample(MaterialDeliveryStatisticCobaltSulfateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    @Delete({
        "delete from material_delivery_statistic_cobalt_sulfate",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    @Insert({
        "insert into material_delivery_statistic_cobalt_sulfate (statistic_code, material_type_code, ",
        "material_code, material_name, ",
        "encoder, delivery_time, ",
        "weights, ni_concentration, ",
        "co_concentration, mn_concentration, ",
        "ni_metallicity, co_metallicity, ",
        "mn_metallicity)",
        "values (#{statisticCode,jdbcType=BIGINT}, #{materialTypeCode,jdbcType=INTEGER}, ",
        "#{materialCode,jdbcType=INTEGER}, #{materialName,jdbcType=VARCHAR}, ",
        "#{encoder,jdbcType=VARCHAR}, #{deliveryTime,jdbcType=TIMESTAMP}, ",
        "#{weights,jdbcType=REAL}, #{niConcentration,jdbcType=REAL}, ",
        "#{coConcentration,jdbcType=REAL}, #{mnConcentration,jdbcType=REAL}, ",
        "#{niMetallicity,jdbcType=REAL}, #{coMetallicity,jdbcType=REAL}, ",
        "#{mnMetallicity,jdbcType=REAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(MaterialDeliveryStatisticCobaltSulfate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    int insertSelective(MaterialDeliveryStatisticCobaltSulfate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    List<MaterialDeliveryStatisticCobaltSulfate> selectByExample(MaterialDeliveryStatisticCobaltSulfateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, statistic_code, material_type_code, material_code, material_name, encoder, ",
        "delivery_time, weights, ni_concentration, co_concentration, mn_concentration, ",
        "ni_metallicity, co_metallicity, mn_metallicity",
        "from material_delivery_statistic_cobalt_sulfate",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    MaterialDeliveryStatisticCobaltSulfate selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MaterialDeliveryStatisticCobaltSulfate record, @Param("example") MaterialDeliveryStatisticCobaltSulfateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MaterialDeliveryStatisticCobaltSulfate record, @Param("example") MaterialDeliveryStatisticCobaltSulfateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaterialDeliveryStatisticCobaltSulfate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_cobalt_sulfate
     *
     * @mbggenerated
     */
    @Update({
        "update material_delivery_statistic_cobalt_sulfate",
        "set statistic_code = #{statisticCode,jdbcType=BIGINT},",
          "material_type_code = #{materialTypeCode,jdbcType=INTEGER},",
          "material_code = #{materialCode,jdbcType=INTEGER},",
          "material_name = #{materialName,jdbcType=VARCHAR},",
          "encoder = #{encoder,jdbcType=VARCHAR},",
          "delivery_time = #{deliveryTime,jdbcType=TIMESTAMP},",
          "weights = #{weights,jdbcType=REAL},",
          "ni_concentration = #{niConcentration,jdbcType=REAL},",
          "co_concentration = #{coConcentration,jdbcType=REAL},",
          "mn_concentration = #{mnConcentration,jdbcType=REAL},",
          "ni_metallicity = #{niMetallicity,jdbcType=REAL},",
          "co_metallicity = #{coMetallicity,jdbcType=REAL},",
          "mn_metallicity = #{mnMetallicity,jdbcType=REAL}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MaterialDeliveryStatisticCobaltSulfate record);
}