package com.jinchi.common.mapper;

import com.jinchi.common.domain.MaterialDeliveryStatisticHead;
import com.jinchi.common.domain.MaterialDeliveryStatisticHeadExample;
import com.jinchi.common.dto.MaterialDeliveryStatisticHeadDTO;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface MaterialDeliveryStatisticHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    int countByExample(MaterialDeliveryStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    int deleteByExample(MaterialDeliveryStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    @Delete({
        "delete from material_delivery_statistic_head",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    @Insert({
        "insert into material_delivery_statistic_head (code, period_code, ",
        "line_name, start_time, ",
        "end_time, flag)",
        "values (#{code,jdbcType=BIGINT}, #{periodCode,jdbcType=INTEGER}, ",
        "#{lineName,jdbcType=INTEGER}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{flag,jdbcType=TINYINT})"
    })
    int insert(MaterialDeliveryStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    int insertSelective(MaterialDeliveryStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    List<MaterialDeliveryStatisticHead> selectByExample(MaterialDeliveryStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, period_code, line_name, start_time, end_time, flag",
        "from material_delivery_statistic_head",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    MaterialDeliveryStatisticHead selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MaterialDeliveryStatisticHead record, @Param("example") MaterialDeliveryStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MaterialDeliveryStatisticHead record, @Param("example") MaterialDeliveryStatisticHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaterialDeliveryStatisticHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_head
     *
     * @mbggenerated
     */
    @Update({
        "update material_delivery_statistic_head",
        "set period_code = #{periodCode,jdbcType=INTEGER},",
          "line_name = #{lineName,jdbcType=INTEGER},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "flag = #{flag,jdbcType=TINYINT}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MaterialDeliveryStatisticHead record);

    List<MaterialDeliveryStatisticHeadDTO> selectByConditions(@Param("sql") String sql);
}