package com.jinchi.common.mapper;

import com.jinchi.common.domain.ProductionBatchAssayMap;
import com.jinchi.common.domain.ProductionBatchAssayMapExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
@Mapper
public interface ProductionBatchAssayMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    int countByExample(ProductionBatchAssayMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    int deleteByExample(ProductionBatchAssayMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    @Insert({
        "insert into production_batch_assay_map (code, batch_code, ",
        "batch, sample_code, ",
        "type, deliverer_id, ",
        "sample_delivering_date, delivery_factory_id, ",
        "test_items, rule_detail_code, ",
        "rule_value, start_time, ",
        "end_time)",
        "values (#{code,jdbcType=BIGINT}, #{batchCode,jdbcType=BIGINT}, ",
        "#{batch,jdbcType=VARCHAR}, #{sampleCode,jdbcType=BIGINT}, ",
        "#{type,jdbcType=INTEGER}, #{delivererId,jdbcType=INTEGER}, ",
        "#{sampleDeliveringDate,jdbcType=TIMESTAMP}, #{deliveryFactoryId,jdbcType=INTEGER}, ",
        "#{testItems,jdbcType=VARCHAR}, #{ruleDetailCode,jdbcType=SMALLINT}, ",
        "#{ruleValue,jdbcType=VARCHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP})"
    })
    int insert(ProductionBatchAssayMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    int insertSelective(ProductionBatchAssayMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    List<ProductionBatchAssayMap> selectByExample(ProductionBatchAssayMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductionBatchAssayMap record, @Param("example") ProductionBatchAssayMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_batch_assay_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductionBatchAssayMap record, @Param("example") ProductionBatchAssayMapExample example);
}