package com.jinchi.common.mapper;

import com.jinchi.common.domain.ProductionLineCellMap;
import com.jinchi.common.domain.ProductionLineCellMapExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface ProductionLineCellMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    int countByExample(ProductionLineCellMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    int deleteByExample(ProductionLineCellMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    @Insert({
        "insert into production_line_cell_map (code, production_line, ",
        "cell_num)",
        "values (#{code,jdbcType=TINYINT}, #{productionLine,jdbcType=VARCHAR}, ",
        "#{cellNum,jdbcType=VARCHAR})"
    })
    int insert(ProductionLineCellMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    int insertSelective(ProductionLineCellMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    List<ProductionLineCellMap> selectByExample(ProductionLineCellMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductionLineCellMap record, @Param("example") ProductionLineCellMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_line_cell_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductionLineCellMap record, @Param("example") ProductionLineCellMapExample example);
}