package com.jinchi.common.mapper;

import com.jinchi.common.domain.QualitySampleDeliveringBatch;
import com.jinchi.common.domain.QualitySampleDeliveringBatchExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface QualitySampleDeliveringBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int countByExample(QualitySampleDeliveringBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int deleteByExample(QualitySampleDeliveringBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int insert(QualitySampleDeliveringBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int insertSelective(QualitySampleDeliveringBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    List<QualitySampleDeliveringBatch> selectByExample(QualitySampleDeliveringBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    QualitySampleDeliveringBatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") QualitySampleDeliveringBatch record, @Param("example") QualitySampleDeliveringBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int updateByExample(@Param("record") QualitySampleDeliveringBatch record, @Param("example") QualitySampleDeliveringBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int updateByPrimaryKeySelective(QualitySampleDeliveringBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_sample_delivering_batch
     *
     * @mbggenerated Sun Jul 12 16:33:05 CST 2020
     */
    int updateByPrimaryKey(QualitySampleDeliveringBatch record);
}