package com.jinchi.common.mapper;

import com.jinchi.common.domain.QualityBaseDetectItem;
import com.jinchi.common.domain.QualityBaseDetectItemExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface QualityBaseDetectItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    int countByExample(QualityBaseDetectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    int deleteByExample(QualityBaseDetectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    @Delete({
        "delete from quality_base_detect_item",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    @Insert({
        "insert into quality_base_detect_item (name)",
        "values (#{name,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="code", before=false, resultType=Long.class)
    int insert(QualityBaseDetectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    int insertSelective(QualityBaseDetectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    List<QualityBaseDetectItem> selectByExample(QualityBaseDetectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, name",
        "from quality_base_detect_item",
        "where code = #{code,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    QualityBaseDetectItem selectByPrimaryKey(Long code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QualityBaseDetectItem record, @Param("example") QualityBaseDetectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QualityBaseDetectItem record, @Param("example") QualityBaseDetectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QualityBaseDetectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_base_detect_item
     *
     * @mbggenerated
     */
    @Update({
        "update quality_base_detect_item",
        "set name = #{name,jdbcType=VARCHAR}",
        "where code = #{code,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(QualityBaseDetectItem record);
}