package com.jinchi.common.mapper;

import com.jinchi.common.domain.SwmsBasicStockAgingRange;
import com.jinchi.common.domain.SwmsBasicStockAgingRangeExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface SwmsBasicStockAgingRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    int countByExample(SwmsBasicStockAgingRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    int deleteByExample(SwmsBasicStockAgingRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SWMS_basic_stock_aging_range",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SWMS_basic_stock_aging_range (query_time, aging_range1a, ",
        "aging_range1b, aging_range2a, ",
        "aging_range2b, aging_range3a, ",
        "aging_range3b, aging_range4a, ",
        "aging_range4b, aging_range5a, ",
        "aging_range5b, aging_end)",
        "values (#{queryTime,jdbcType=TIMESTAMP}, #{agingRange1a,jdbcType=INTEGER}, ",
        "#{agingRange1b,jdbcType=INTEGER}, #{agingRange2a,jdbcType=INTEGER}, ",
        "#{agingRange2b,jdbcType=INTEGER}, #{agingRange3a,jdbcType=INTEGER}, ",
        "#{agingRange3b,jdbcType=INTEGER}, #{agingRange4a,jdbcType=INTEGER}, ",
        "#{agingRange4b,jdbcType=INTEGER}, #{agingRange5a,jdbcType=INTEGER}, ",
        "#{agingRange5b,jdbcType=INTEGER}, #{agingEnd,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SwmsBasicStockAgingRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    int insertSelective(SwmsBasicStockAgingRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    List<SwmsBasicStockAgingRange> selectByExample(SwmsBasicStockAgingRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, query_time, aging_range1a, aging_range1b, aging_range2a, aging_range2b, ",
        "aging_range3a, aging_range3b, aging_range4a, aging_range4b, aging_range5a, aging_range5b, ",
        "aging_end",
        "from SWMS_basic_stock_aging_range",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SwmsBasicStockAgingRange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SwmsBasicStockAgingRange record, @Param("example") SwmsBasicStockAgingRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SwmsBasicStockAgingRange record, @Param("example") SwmsBasicStockAgingRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SwmsBasicStockAgingRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_basic_stock_aging_range
     *
     * @mbggenerated
     */
    @Update({
        "update SWMS_basic_stock_aging_range",
        "set query_time = #{queryTime,jdbcType=TIMESTAMP},",
          "aging_range1a = #{agingRange1a,jdbcType=INTEGER},",
          "aging_range1b = #{agingRange1b,jdbcType=INTEGER},",
          "aging_range2a = #{agingRange2a,jdbcType=INTEGER},",
          "aging_range2b = #{agingRange2b,jdbcType=INTEGER},",
          "aging_range3a = #{agingRange3a,jdbcType=INTEGER},",
          "aging_range3b = #{agingRange3b,jdbcType=INTEGER},",
          "aging_range4a = #{agingRange4a,jdbcType=INTEGER},",
          "aging_range4b = #{agingRange4b,jdbcType=INTEGER},",
          "aging_range5a = #{agingRange5a,jdbcType=INTEGER},",
          "aging_range5b = #{agingRange5b,jdbcType=INTEGER},",
          "aging_end = #{agingEnd,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SwmsBasicStockAgingRange record);
}