package com.jinchi.common.mapper;

import com.jinchi.common.domain.SwmsStockInJournalAccount;
import com.jinchi.common.domain.SwmsStockInJournalAccountExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface SwmsStockInJournalAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    int countByExample(SwmsStockInJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    int deleteByExample(SwmsStockInJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SWMS_stock_in_journal_account",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SWMS_stock_in_journal_account (material_code, created_time, ",
        "created_person, flag)",
        "values (#{materialCode,jdbcType=VARCHAR}, #{createdTime,jdbcType=TIMESTAMP}, ",
        "#{createdPerson,jdbcType=VARCHAR}, #{flag,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SwmsStockInJournalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    int insertSelective(SwmsStockInJournalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    List<SwmsStockInJournalAccount> selectByExample(SwmsStockInJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, material_code, created_time, created_person, flag",
        "from SWMS_stock_in_journal_account",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SwmsStockInJournalAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SwmsStockInJournalAccount record, @Param("example") SwmsStockInJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SwmsStockInJournalAccount record, @Param("example") SwmsStockInJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SwmsStockInJournalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_journal_account
     *
     * @mbggenerated
     */
    @Update({
        "update SWMS_stock_in_journal_account",
        "set material_code = #{materialCode,jdbcType=VARCHAR},",
          "created_time = #{createdTime,jdbcType=TIMESTAMP},",
          "created_person = #{createdPerson,jdbcType=VARCHAR},",
          "flag = #{flag,jdbcType=BIT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SwmsStockInJournalAccount record);
}