package com.jinchi.common.mapper;

import com.jinchi.common.domain.SwmsStockInventoryDailyReports;
import com.jinchi.common.domain.SwmsStockInventoryDailyReportsExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface SwmsStockInventoryDailyReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    int countByExample(SwmsStockInventoryDailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    int deleteByExample(SwmsStockInventoryDailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SWMS_stock_inventory_daily_reports",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SWMS_stock_inventory_daily_reports (material_type_id, material_sub_type_id, ",
        "material_name_code, material_supplier_code, ",
        "material_name, measure_unit, ",
        "last_weight, current_in_record, ",
        "current_out_record, weight, ",
        "safity_inventory, stock_date, ",
        "comments)",
        "values (#{materialTypeId,jdbcType=INTEGER}, #{materialSubTypeId,jdbcType=INTEGER}, ",
        "#{materialNameCode,jdbcType=INTEGER}, #{materialSupplierCode,jdbcType=INTEGER}, ",
        "#{materialName,jdbcType=VARCHAR}, #{measureUnit,jdbcType=VARCHAR}, ",
        "#{lastWeight,jdbcType=REAL}, #{currentInRecord,jdbcType=REAL}, ",
        "#{currentOutRecord,jdbcType=REAL}, #{weight,jdbcType=REAL}, ",
        "#{safityInventory,jdbcType=REAL}, #{stockDate,jdbcType=TIMESTAMP}, ",
        "#{comments,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SwmsStockInventoryDailyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    int insertSelective(SwmsStockInventoryDailyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    List<SwmsStockInventoryDailyReports> selectByExample(SwmsStockInventoryDailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, material_type_id, material_sub_type_id, material_name_code, material_supplier_code, ",
        "material_name, measure_unit, last_weight, current_in_record, current_out_record, ",
        "weight, safity_inventory, stock_date, comments",
        "from SWMS_stock_inventory_daily_reports",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SwmsStockInventoryDailyReports selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SwmsStockInventoryDailyReports record, @Param("example") SwmsStockInventoryDailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SwmsStockInventoryDailyReports record, @Param("example") SwmsStockInventoryDailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SwmsStockInventoryDailyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_daily_reports
     *
     * @mbggenerated
     */
    @Update({
        "update SWMS_stock_inventory_daily_reports",
        "set material_type_id = #{materialTypeId,jdbcType=INTEGER},",
          "material_sub_type_id = #{materialSubTypeId,jdbcType=INTEGER},",
          "material_name_code = #{materialNameCode,jdbcType=INTEGER},",
          "material_supplier_code = #{materialSupplierCode,jdbcType=INTEGER},",
          "material_name = #{materialName,jdbcType=VARCHAR},",
          "measure_unit = #{measureUnit,jdbcType=VARCHAR},",
          "last_weight = #{lastWeight,jdbcType=REAL},",
          "current_in_record = #{currentInRecord,jdbcType=REAL},",
          "current_out_record = #{currentOutRecord,jdbcType=REAL},",
          "weight = #{weight,jdbcType=REAL},",
          "safity_inventory = #{safityInventory,jdbcType=REAL},",
          "stock_date = #{stockDate,jdbcType=TIMESTAMP},",
          "comments = #{comments,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SwmsStockInventoryDailyReports record);
}