package com.jinchi.common.mapper;

import com.jinchi.common.domain.SwmsStockInventoryReallyReports;
import com.jinchi.common.domain.SwmsStockInventoryReallyReportsExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface SwmsStockInventoryReallyReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    int countByExample(SwmsStockInventoryReallyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    int deleteByExample(SwmsStockInventoryReallyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SWMS_stock_inventory_really_reports",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SWMS_stock_inventory_really_reports (material_type_id, material_sub_type_id, ",
        "material_name_code, material_supplier_code, ",
        "material_name, material_batch, ",
        "measure_unit, check_status, ",
        "real_weight, useful_weight, ",
        "stock_date)",
        "values (#{materialTypeId,jdbcType=INTEGER}, #{materialSubTypeId,jdbcType=INTEGER}, ",
        "#{materialNameCode,jdbcType=INTEGER}, #{materialSupplierCode,jdbcType=INTEGER}, ",
        "#{materialName,jdbcType=VARCHAR}, #{materialBatch,jdbcType=VARCHAR}, ",
        "#{measureUnit,jdbcType=VARCHAR}, #{checkStatus,jdbcType=TINYINT}, ",
        "#{realWeight,jdbcType=REAL}, #{usefulWeight,jdbcType=REAL}, ",
        "#{stockDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SwmsStockInventoryReallyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    int insertSelective(SwmsStockInventoryReallyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    List<SwmsStockInventoryReallyReports> selectByExample(SwmsStockInventoryReallyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, material_type_id, material_sub_type_id, material_name_code, material_supplier_code, ",
        "material_name, material_batch, measure_unit, check_status, real_weight, useful_weight, ",
        "stock_date",
        "from SWMS_stock_inventory_really_reports",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SwmsStockInventoryReallyReports selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SwmsStockInventoryReallyReports record, @Param("example") SwmsStockInventoryReallyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SwmsStockInventoryReallyReports record, @Param("example") SwmsStockInventoryReallyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SwmsStockInventoryReallyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_inventory_really_reports
     *
     * @mbggenerated
     */
    @Update({
        "update SWMS_stock_inventory_really_reports",
        "set material_type_id = #{materialTypeId,jdbcType=INTEGER},",
          "material_sub_type_id = #{materialSubTypeId,jdbcType=INTEGER},",
          "material_name_code = #{materialNameCode,jdbcType=INTEGER},",
          "material_supplier_code = #{materialSupplierCode,jdbcType=INTEGER},",
          "material_name = #{materialName,jdbcType=VARCHAR},",
          "material_batch = #{materialBatch,jdbcType=VARCHAR},",
          "measure_unit = #{measureUnit,jdbcType=VARCHAR},",
          "check_status = #{checkStatus,jdbcType=TINYINT},",
          "real_weight = #{realWeight,jdbcType=REAL},",
          "useful_weight = #{usefulWeight,jdbcType=REAL},",
          "stock_date = #{stockDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SwmsStockInventoryReallyReports record);
}