package com.jinchi.common.mapper;

import com.jinchi.common.domain.SwmsStockOutRecordDetail;
import com.jinchi.common.domain.SwmsStockOutRecordDetailExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface SwmsStockOutRecordDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    int countByExample(SwmsStockOutRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    int deleteByExample(SwmsStockOutRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SWMS_stock_out_record_detail",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SWMS_stock_out_record_detail (stock_out_record_id, stock_out_record_head_id, ",
        "stock_out_record_head_code, group_name, ",
        "stock_in_record_account_id, material_code, ",
        "material_batch, material_type_id, ",
        "material_sub_type_id, material_workshop_id, ",
        "material_name_code, material_supplier_code, ",
        "material_name, bag_num, ",
        "weight, measure_unit, ",
        "created_time, completion_flag)",
        "values (#{stockOutRecordId,jdbcType=BIGINT}, #{stockOutRecordHeadId,jdbcType=BIGINT}, ",
        "#{stockOutRecordHeadCode,jdbcType=BIGINT}, #{groupName,jdbcType=VARCHAR}, ",
        "#{stockInRecordAccountId,jdbcType=BIGINT}, #{materialCode,jdbcType=VARCHAR}, ",
        "#{materialBatch,jdbcType=VARCHAR}, #{materialTypeId,jdbcType=INTEGER}, ",
        "#{materialSubTypeId,jdbcType=INTEGER}, #{materialWorkshopId,jdbcType=INTEGER}, ",
        "#{materialNameCode,jdbcType=INTEGER}, #{materialSupplierCode,jdbcType=INTEGER}, ",
        "#{materialName,jdbcType=VARCHAR}, #{bagNum,jdbcType=INTEGER}, ",
        "#{weight,jdbcType=REAL}, #{measureUnit,jdbcType=VARCHAR}, ",
        "#{createdTime,jdbcType=TIMESTAMP}, #{completionFlag,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SwmsStockOutRecordDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    int insertSelective(SwmsStockOutRecordDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    List<SwmsStockOutRecordDetail> selectByExample(SwmsStockOutRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, stock_out_record_id, stock_out_record_head_id, stock_out_record_head_code, ",
        "group_name, stock_in_record_account_id, material_code, material_batch, material_type_id, ",
        "material_sub_type_id, material_workshop_id, material_name_code, material_supplier_code, ",
        "material_name, bag_num, weight, measure_unit, created_time, completion_flag",
        "from SWMS_stock_out_record_detail",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SwmsStockOutRecordDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SwmsStockOutRecordDetail record, @Param("example") SwmsStockOutRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SwmsStockOutRecordDetail record, @Param("example") SwmsStockOutRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SwmsStockOutRecordDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_detail
     *
     * @mbggenerated
     */
    @Update({
        "update SWMS_stock_out_record_detail",
        "set stock_out_record_id = #{stockOutRecordId,jdbcType=BIGINT},",
          "stock_out_record_head_id = #{stockOutRecordHeadId,jdbcType=BIGINT},",
          "stock_out_record_head_code = #{stockOutRecordHeadCode,jdbcType=BIGINT},",
          "group_name = #{groupName,jdbcType=VARCHAR},",
          "stock_in_record_account_id = #{stockInRecordAccountId,jdbcType=BIGINT},",
          "material_code = #{materialCode,jdbcType=VARCHAR},",
          "material_batch = #{materialBatch,jdbcType=VARCHAR},",
          "material_type_id = #{materialTypeId,jdbcType=INTEGER},",
          "material_sub_type_id = #{materialSubTypeId,jdbcType=INTEGER},",
          "material_workshop_id = #{materialWorkshopId,jdbcType=INTEGER},",
          "material_name_code = #{materialNameCode,jdbcType=INTEGER},",
          "material_supplier_code = #{materialSupplierCode,jdbcType=INTEGER},",
          "material_name = #{materialName,jdbcType=VARCHAR},",
          "bag_num = #{bagNum,jdbcType=INTEGER},",
          "weight = #{weight,jdbcType=REAL},",
          "measure_unit = #{measureUnit,jdbcType=VARCHAR},",
          "created_time = #{createdTime,jdbcType=TIMESTAMP},",
          "completion_flag = #{completionFlag,jdbcType=BIT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SwmsStockOutRecordDetail record);
}