package com.jinchi.common.mapper;

import com.jinchi.common.domain.TechniqueBaseRawBindManufacturer;
import com.jinchi.common.domain.TechniqueBaseRawBindManufacturerExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface TechniqueBaseRawBindManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int countByExample(TechniqueBaseRawBindManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int deleteByExample(TechniqueBaseRawBindManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int insert(TechniqueBaseRawBindManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int insertSelective(TechniqueBaseRawBindManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    List<TechniqueBaseRawBindManufacturer> selectByExample(TechniqueBaseRawBindManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    TechniqueBaseRawBindManufacturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") TechniqueBaseRawBindManufacturer record, @Param("example") TechniqueBaseRawBindManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int updateByExample(@Param("record") TechniqueBaseRawBindManufacturer record, @Param("example") TechniqueBaseRawBindManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int updateByPrimaryKeySelective(TechniqueBaseRawBindManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_raw_bind_manufacturer
     *
     * @mbggenerated Thu Jun 18 20:43:51 CST 2020
     */
    int updateByPrimaryKey(TechniqueBaseRawBindManufacturer record);
}