package com.jinchi.common.mapper;

import com.jinchi.common.domain.TechniqueBaseProductMaterial;
import com.jinchi.common.domain.TechniqueBaseProductMaterialExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface TechniqueBaseProductMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    int countByExample(TechniqueBaseProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    int deleteByExample(TechniqueBaseProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    @Insert({
        "insert into technique_base_product_material (id, name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(TechniqueBaseProductMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    int insertSelective(TechniqueBaseProductMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    List<TechniqueBaseProductMaterial> selectByExample(TechniqueBaseProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TechniqueBaseProductMaterial record, @Param("example") TechniqueBaseProductMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_base_product_material
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TechniqueBaseProductMaterial record, @Param("example") TechniqueBaseProductMaterialExample example);
}