package com.jinchi.common.mapper;

import com.jinchi.common.domain.TraceabilityBeforeDisassembly;
import com.jinchi.common.domain.TraceabilityBeforeDisassemblyExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component
public interface TraceabilityBeforeDisassemblyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    int countByExample(TraceabilityBeforeDisassemblyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    int deleteByExample(TraceabilityBeforeDisassemblyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    @Delete({
        "delete from traceability_before_disassembly",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    @Insert({
        "insert into traceability_before_disassembly (BatteryPackTraceCode, ModuleTraceCode, ",
        "SingleTraceCode)",
        "values (#{batterypacktracecode,jdbcType=VARCHAR}, #{moduletracecode,jdbcType=VARCHAR}, ",
        "#{singletracecode,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TraceabilityBeforeDisassembly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    int insertSelective(TraceabilityBeforeDisassembly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    List<TraceabilityBeforeDisassembly> selectByExample(TraceabilityBeforeDisassemblyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, BatteryPackTraceCode, ModuleTraceCode, SingleTraceCode",
        "from traceability_before_disassembly",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TraceabilityBeforeDisassembly selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TraceabilityBeforeDisassembly record, @Param("example") TraceabilityBeforeDisassemblyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TraceabilityBeforeDisassembly record, @Param("example") TraceabilityBeforeDisassemblyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraceabilityBeforeDisassembly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceabilitybeforedisassembly
     *
     * @mbggenerated
     */
    @Update({
        "update traceability_before_disassembly",
        "set BatteryPackTraceCode = #{batterypacktracecode,jdbcType=VARCHAR},",
          "ModuleTraceCode = #{moduletracecode,jdbcType=VARCHAR},",
          "SingleTraceCode = #{singletracecode,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TraceabilityBeforeDisassembly record);
}
