package com.jinchi.common.domain;

public class AnodeGoodsInProcessStatisticSmash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.statistic_code
     *
     * @mbggenerated
     */
    private Long statisticCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.material_code
     *
     * @mbggenerated
     */
    private Integer materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.line_code
     *
     * @mbggenerated
     */
    private Integer lineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.type_code
     *
     * @mbggenerated
     */
    private Integer typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.process_code
     *
     * @mbggenerated
     */
    private Integer processCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.feedstock
     *
     * @mbggenerated
     */
    private Float feedstock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.consume
     *
     * @mbggenerated
     */
    private Float consume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anode_goods_in_process_statistic_smash.balance
     *
     * @mbggenerated
     */
    private Float balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_smash
     *
     * @mbggenerated
     */
    public AnodeGoodsInProcessStatisticSmash(Long code, Long statisticCode, Integer materialCode, Integer lineCode, Integer typeCode, Integer processCode, Float feedstock, Float consume, Float balance) {
        this.code = code;
        this.statisticCode = statisticCode;
        this.materialCode = materialCode;
        this.lineCode = lineCode;
        this.typeCode = typeCode;
        this.processCode = processCode;
        this.feedstock = feedstock;
        this.consume = consume;
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anode_goods_in_process_statistic_smash
     *
     * @mbggenerated
     */
    public AnodeGoodsInProcessStatisticSmash() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.code
     *
     * @return the value of anode_goods_in_process_statistic_smash.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.code
     *
     * @param code the value for anode_goods_in_process_statistic_smash.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.statistic_code
     *
     * @return the value of anode_goods_in_process_statistic_smash.statistic_code
     *
     * @mbggenerated
     */
    public Long getStatisticCode() {
        return statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.statistic_code
     *
     * @param statisticCode the value for anode_goods_in_process_statistic_smash.statistic_code
     *
     * @mbggenerated
     */
    public void setStatisticCode(Long statisticCode) {
        this.statisticCode = statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.material_code
     *
     * @return the value of anode_goods_in_process_statistic_smash.material_code
     *
     * @mbggenerated
     */
    public Integer getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.material_code
     *
     * @param materialCode the value for anode_goods_in_process_statistic_smash.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(Integer materialCode) {
        this.materialCode = materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.line_code
     *
     * @return the value of anode_goods_in_process_statistic_smash.line_code
     *
     * @mbggenerated
     */
    public Integer getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.line_code
     *
     * @param lineCode the value for anode_goods_in_process_statistic_smash.line_code
     *
     * @mbggenerated
     */
    public void setLineCode(Integer lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.type_code
     *
     * @return the value of anode_goods_in_process_statistic_smash.type_code
     *
     * @mbggenerated
     */
    public Integer getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.type_code
     *
     * @param typeCode the value for anode_goods_in_process_statistic_smash.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(Integer typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.process_code
     *
     * @return the value of anode_goods_in_process_statistic_smash.process_code
     *
     * @mbggenerated
     */
    public Integer getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.process_code
     *
     * @param processCode the value for anode_goods_in_process_statistic_smash.process_code
     *
     * @mbggenerated
     */
    public void setProcessCode(Integer processCode) {
        this.processCode = processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.feedstock
     *
     * @return the value of anode_goods_in_process_statistic_smash.feedstock
     *
     * @mbggenerated
     */
    public Float getFeedstock() {
        return feedstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.feedstock
     *
     * @param feedstock the value for anode_goods_in_process_statistic_smash.feedstock
     *
     * @mbggenerated
     */
    public void setFeedstock(Float feedstock) {
        this.feedstock = feedstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.consume
     *
     * @return the value of anode_goods_in_process_statistic_smash.consume
     *
     * @mbggenerated
     */
    public Float getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.consume
     *
     * @param consume the value for anode_goods_in_process_statistic_smash.consume
     *
     * @mbggenerated
     */
    public void setConsume(Float consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anode_goods_in_process_statistic_smash.balance
     *
     * @return the value of anode_goods_in_process_statistic_smash.balance
     *
     * @mbggenerated
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anode_goods_in_process_statistic_smash.balance
     *
     * @param balance the value for anode_goods_in_process_statistic_smash.balance
     *
     * @mbggenerated
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }
}