package com.jinchi.common.domain;

public class AuxiliaryMaterialsStatisticDetailsTankArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.statistic_code
     *
     * @mbggenerated
     */
    private Long statisticCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.process_code
     *
     * @mbggenerated
     */
    private Integer processCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.material_code
     *
     * @mbggenerated
     */
    private Integer materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.volumes
     *
     * @mbggenerated
     */
    private Float volumes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.density
     *
     * @mbggenerated
     */
    private Float density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.totals
     *
     * @mbggenerated
     */
    private Float totals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.ammonia_concentration
     *
     * @mbggenerated
     */
    private Float ammoniaConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.alkali_concentration
     *
     * @mbggenerated
     */
    private Float alkaliConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.ammonia_value
     *
     * @mbggenerated
     */
    private Float ammoniaValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auxiliary_materials_statistic_details_tank_area.alkali_value
     *
     * @mbggenerated
     */
    private Float alkaliValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_details_tank_area
     *
     * @mbggenerated
     */
    public AuxiliaryMaterialsStatisticDetailsTankArea(Long code, Long statisticCode, Integer processCode, Integer materialCode, Float volumes, Float density, Float totals, Float ammoniaConcentration, Float alkaliConcentration, Float ammoniaValue, Float alkaliValue) {
        this.code = code;
        this.statisticCode = statisticCode;
        this.processCode = processCode;
        this.materialCode = materialCode;
        this.volumes = volumes;
        this.density = density;
        this.totals = totals;
        this.ammoniaConcentration = ammoniaConcentration;
        this.alkaliConcentration = alkaliConcentration;
        this.ammoniaValue = ammoniaValue;
        this.alkaliValue = alkaliValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auxiliary_materials_statistic_details_tank_area
     *
     * @mbggenerated
     */
    public AuxiliaryMaterialsStatisticDetailsTankArea() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.code
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.code
     *
     * @param code the value for auxiliary_materials_statistic_details_tank_area.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.statistic_code
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.statistic_code
     *
     * @mbggenerated
     */
    public Long getStatisticCode() {
        return statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.statistic_code
     *
     * @param statisticCode the value for auxiliary_materials_statistic_details_tank_area.statistic_code
     *
     * @mbggenerated
     */
    public void setStatisticCode(Long statisticCode) {
        this.statisticCode = statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.process_code
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.process_code
     *
     * @mbggenerated
     */
    public Integer getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.process_code
     *
     * @param processCode the value for auxiliary_materials_statistic_details_tank_area.process_code
     *
     * @mbggenerated
     */
    public void setProcessCode(Integer processCode) {
        this.processCode = processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.material_code
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.material_code
     *
     * @mbggenerated
     */
    public Integer getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.material_code
     *
     * @param materialCode the value for auxiliary_materials_statistic_details_tank_area.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(Integer materialCode) {
        this.materialCode = materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.volumes
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.volumes
     *
     * @mbggenerated
     */
    public Float getVolumes() {
        return volumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.volumes
     *
     * @param volumes the value for auxiliary_materials_statistic_details_tank_area.volumes
     *
     * @mbggenerated
     */
    public void setVolumes(Float volumes) {
        this.volumes = volumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.density
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.density
     *
     * @mbggenerated
     */
    public Float getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.density
     *
     * @param density the value for auxiliary_materials_statistic_details_tank_area.density
     *
     * @mbggenerated
     */
    public void setDensity(Float density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.totals
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.totals
     *
     * @mbggenerated
     */
    public Float getTotals() {
        return totals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.totals
     *
     * @param totals the value for auxiliary_materials_statistic_details_tank_area.totals
     *
     * @mbggenerated
     */
    public void setTotals(Float totals) {
        this.totals = totals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.ammonia_concentration
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.ammonia_concentration
     *
     * @mbggenerated
     */
    public Float getAmmoniaConcentration() {
        return ammoniaConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.ammonia_concentration
     *
     * @param ammoniaConcentration the value for auxiliary_materials_statistic_details_tank_area.ammonia_concentration
     *
     * @mbggenerated
     */
    public void setAmmoniaConcentration(Float ammoniaConcentration) {
        this.ammoniaConcentration = ammoniaConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.alkali_concentration
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.alkali_concentration
     *
     * @mbggenerated
     */
    public Float getAlkaliConcentration() {
        return alkaliConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.alkali_concentration
     *
     * @param alkaliConcentration the value for auxiliary_materials_statistic_details_tank_area.alkali_concentration
     *
     * @mbggenerated
     */
    public void setAlkaliConcentration(Float alkaliConcentration) {
        this.alkaliConcentration = alkaliConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.ammonia_value
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.ammonia_value
     *
     * @mbggenerated
     */
    public Float getAmmoniaValue() {
        return ammoniaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.ammonia_value
     *
     * @param ammoniaValue the value for auxiliary_materials_statistic_details_tank_area.ammonia_value
     *
     * @mbggenerated
     */
    public void setAmmoniaValue(Float ammoniaValue) {
        this.ammoniaValue = ammoniaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auxiliary_materials_statistic_details_tank_area.alkali_value
     *
     * @return the value of auxiliary_materials_statistic_details_tank_area.alkali_value
     *
     * @mbggenerated
     */
    public Float getAlkaliValue() {
        return alkaliValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auxiliary_materials_statistic_details_tank_area.alkali_value
     *
     * @param alkaliValue the value for auxiliary_materials_statistic_details_tank_area.alkali_value
     *
     * @mbggenerated
     */
    public void setAlkaliValue(Float alkaliValue) {
        this.alkaliValue = alkaliValue;
    }
}