package com.jinchi.common.domain;

public class BasicInfoAnodeProcessName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info_anode_process_name.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info_anode_process_name.process_name
     *
     * @mbggenerated
     */
    private String processName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_process_name
     *
     * @mbggenerated
     */
    public BasicInfoAnodeProcessName(Integer code, String processName) {
        this.code = code;
        this.processName = processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_anode_process_name
     *
     * @mbggenerated
     */
    public BasicInfoAnodeProcessName() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info_anode_process_name.code
     *
     * @return the value of basic_info_anode_process_name.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info_anode_process_name.code
     *
     * @param code the value for basic_info_anode_process_name.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info_anode_process_name.process_name
     *
     * @return the value of basic_info_anode_process_name.process_name
     *
     * @mbggenerated
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info_anode_process_name.process_name
     *
     * @param processName the value for basic_info_anode_process_name.process_name
     *
     * @mbggenerated
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }
}