package com.jinchi.common.domain;

public class BasicInfoEvaluationsItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info_evaluations_item.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info_evaluations_item.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_evaluations_item
     *
     * @mbggenerated
     */
    public BasicInfoEvaluationsItem(Integer code, String itemName) {
        this.code = code;
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info_evaluations_item
     *
     * @mbggenerated
     */
    public BasicInfoEvaluationsItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info_evaluations_item.code
     *
     * @return the value of basic_info_evaluations_item.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info_evaluations_item.code
     *
     * @param code the value for basic_info_evaluations_item.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info_evaluations_item.item_name
     *
     * @return the value of basic_info_evaluations_item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info_evaluations_item.item_name
     *
     * @param itemName the value for basic_info_evaluations_item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }
}