package com.jinchi.common.domain;

public class DeviceUnitAccessory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_unit_accessory.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_unit_accessory.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_unit_accessory.specification
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_unit_accessory.counts
     *
     * @mbggenerated
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_unit_accessory.unit_code
     *
     * @mbggenerated
     */
    private Long unitCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_unit_accessory
     *
     * @mbggenerated
     */
    public DeviceUnitAccessory(Long code, String name, String specification, Integer counts, Long unitCode) {
        this.code = code;
        this.name = name;
        this.specification = specification;
        this.counts = counts;
        this.unitCode = unitCode;
    }
    public DeviceUnitAccessory(){}

    public void setCode(Long code) {
        this.code = code;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setSpecification(String specification) {
        this.specification = specification;
    }

    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    public void setUnitCode(Long unitCode) {
        this.unitCode = unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_unit_accessory.code
     *
     * @return the value of device_unit_accessory.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_unit_accessory.name
     *
     * @return the value of device_unit_accessory.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_unit_accessory.specification
     *
     * @return the value of device_unit_accessory.specification
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_unit_accessory.counts
     *
     * @return the value of device_unit_accessory.counts
     *
     * @mbggenerated
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_unit_accessory.unit_code
     *
     * @return the value of device_unit_accessory.unit_code
     *
     * @mbggenerated
     */
    public Long getUnitCode() {
        return unitCode;
    }
}