package com.jinchi.common.domain;

public class FireMagePpItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.process_code
     *
     * @mbggenerated
     */
    private Integer processCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.process_name
     *
     * @mbggenerated
     */
    private String processName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.product_code
     *
     * @mbggenerated
     */
    private Integer productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.item_codes
     *
     * @mbggenerated
     */
    private String itemCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_pp_items.item_names
     *
     * @mbggenerated
     */
    private String itemNames;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_pp_items
     *
     * @mbggenerated
     */
    public FireMagePpItems(Long code, Integer processCode, String processName, Integer productCode, String productName, String itemCodes, String itemNames) {
        this.code = code;
        this.processCode = processCode;
        this.processName = processName;
        this.productCode = productCode;
        this.productName = productName;
        this.itemCodes = itemCodes;
        this.itemNames = itemNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_pp_items
     *
     * @mbggenerated
     */
    public FireMagePpItems() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.code
     *
     * @return the value of fire_mage_pp_items.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.code
     *
     * @param code the value for fire_mage_pp_items.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.process_code
     *
     * @return the value of fire_mage_pp_items.process_code
     *
     * @mbggenerated
     */
    public Integer getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.process_code
     *
     * @param processCode the value for fire_mage_pp_items.process_code
     *
     * @mbggenerated
     */
    public void setProcessCode(Integer processCode) {
        this.processCode = processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.process_name
     *
     * @return the value of fire_mage_pp_items.process_name
     *
     * @mbggenerated
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.process_name
     *
     * @param processName the value for fire_mage_pp_items.process_name
     *
     * @mbggenerated
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.product_code
     *
     * @return the value of fire_mage_pp_items.product_code
     *
     * @mbggenerated
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.product_code
     *
     * @param productCode the value for fire_mage_pp_items.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.product_name
     *
     * @return the value of fire_mage_pp_items.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.product_name
     *
     * @param productName the value for fire_mage_pp_items.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.item_codes
     *
     * @return the value of fire_mage_pp_items.item_codes
     *
     * @mbggenerated
     */
    public String getItemCodes() {
        return itemCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.item_codes
     *
     * @param itemCodes the value for fire_mage_pp_items.item_codes
     *
     * @mbggenerated
     */
    public void setItemCodes(String itemCodes) {
        this.itemCodes = itemCodes == null ? null : itemCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_pp_items.item_names
     *
     * @return the value of fire_mage_pp_items.item_names
     *
     * @mbggenerated
     */
    public String getItemNames() {
        return itemNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_pp_items.item_names
     *
     * @param itemNames the value for fire_mage_pp_items.item_names
     *
     * @mbggenerated
     */
    public void setItemNames(String itemNames) {
        this.itemNames = itemNames == null ? null : itemNames.trim();
    }
}