package com.jinchi.common.domain;

public class FireMageLabelItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_label_items.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_label_items.item_codes
     *
     * @mbggenerated
     */
    private String itemCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_mage_label_items.item_names
     *
     * @mbggenerated
     */
    private String itemNames;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_label_items
     *
     * @mbggenerated
     */
    public FireMageLabelItems(Long code, String itemCodes, String itemNames) {
        this.code = code;
        this.itemCodes = itemCodes;
        this.itemNames = itemNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_mage_label_items
     *
     * @mbggenerated
     */
    public FireMageLabelItems() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_label_items.code
     *
     * @return the value of fire_mage_label_items.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_label_items.code
     *
     * @param code the value for fire_mage_label_items.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_label_items.item_codes
     *
     * @return the value of fire_mage_label_items.item_codes
     *
     * @mbggenerated
     */
    public String getItemCodes() {
        return itemCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_label_items.item_codes
     *
     * @param itemCodes the value for fire_mage_label_items.item_codes
     *
     * @mbggenerated
     */
    public void setItemCodes(String itemCodes) {
        this.itemCodes = itemCodes == null ? null : itemCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_mage_label_items.item_names
     *
     * @return the value of fire_mage_label_items.item_names
     *
     * @mbggenerated
     */
    public String getItemNames() {
        return itemNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_mage_label_items.item_names
     *
     * @param itemNames the value for fire_mage_label_items.item_names
     *
     * @mbggenerated
     */
    public void setItemNames(String itemNames) {
        this.itemNames = itemNames == null ? null : itemNames.trim();
    }
}