package com.jinchi.common.domain;

public class GoodsInProcessStatisticAgeing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.statistic_code
     *
     * @mbggenerated
     */
    private Long statisticCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.process_code
     *
     * @mbggenerated
     */
    private Integer processCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.material_code
     *
     * @mbggenerated
     */
    private Integer materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.volumes
     *
     * @mbggenerated
     */
    private Float volumes = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.solid_containing_content
     *
     * @mbggenerated
     */
    private Float solidContainingContent = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.weight
     *
     * @mbggenerated
     */
    private Float weight = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.Ni_concentration
     *
     * @mbggenerated
     */
    private Float niConcentration = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.Co_concentration
     *
     * @mbggenerated
     */
    private Float coConcentration = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.Mn_concentration
     *
     * @mbggenerated
     */
    private Float mnConcentration = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.Ni_metallicity
     *
     * @mbggenerated
     */
    private Float niMetallicity = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.Co_metallicity
     *
     * @mbggenerated
     */
    private Float coMetallicity = 0f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_in_process_statistic_ageing.Mn_metallicity
     *
     * @mbggenerated
     */
    private Float mnMetallicity = 0f;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_ageing
     *
     * @mbggenerated
     */
    public GoodsInProcessStatisticAgeing(Integer code, Long statisticCode, Integer processCode, Integer materialCode, Float volumes, Float solidContainingContent, Float weight, Float niConcentration, Float coConcentration, Float mnConcentration, Float niMetallicity, Float coMetallicity, Float mnMetallicity) {
        this.code = code;
        this.statisticCode = statisticCode;
        this.processCode = processCode;
        this.materialCode = materialCode;
        this.volumes = volumes;
        this.solidContainingContent = solidContainingContent;
        this.weight = weight;
        this.niConcentration = niConcentration;
        this.coConcentration = coConcentration;
        this.mnConcentration = mnConcentration;
        this.niMetallicity = niMetallicity;
        this.coMetallicity = coMetallicity;
        this.mnMetallicity = mnMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_in_process_statistic_ageing
     *
     * @mbggenerated
     */
    public GoodsInProcessStatisticAgeing() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.code
     *
     * @return the value of goods_in_process_statistic_ageing.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.code
     *
     * @param code the value for goods_in_process_statistic_ageing.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.statistic_code
     *
     * @return the value of goods_in_process_statistic_ageing.statistic_code
     *
     * @mbggenerated
     */
    public Long getStatisticCode() {
        return statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.statistic_code
     *
     * @param statisticCode the value for goods_in_process_statistic_ageing.statistic_code
     *
     * @mbggenerated
     */
    public void setStatisticCode(Long statisticCode) {
        this.statisticCode = statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.process_code
     *
     * @return the value of goods_in_process_statistic_ageing.process_code
     *
     * @mbggenerated
     */
    public Integer getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.process_code
     *
     * @param processCode the value for goods_in_process_statistic_ageing.process_code
     *
     * @mbggenerated
     */
    public void setProcessCode(Integer processCode) {
        this.processCode = processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.material_code
     *
     * @return the value of goods_in_process_statistic_ageing.material_code
     *
     * @mbggenerated
     */
    public Integer getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.material_code
     *
     * @param materialCode the value for goods_in_process_statistic_ageing.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(Integer materialCode) {
        this.materialCode = materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.volumes
     *
     * @return the value of goods_in_process_statistic_ageing.volumes
     *
     * @mbggenerated
     */
    public Float getVolumes() {
        return volumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.volumes
     *
     * @param volumes the value for goods_in_process_statistic_ageing.volumes
     *
     * @mbggenerated
     */
    public void setVolumes(Float volumes) {
        this.volumes = volumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.solid_containing_content
     *
     * @return the value of goods_in_process_statistic_ageing.solid_containing_content
     *
     * @mbggenerated
     */
    public Float getSolidContainingContent() {
        return solidContainingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.solid_containing_content
     *
     * @param solidContainingContent the value for goods_in_process_statistic_ageing.solid_containing_content
     *
     * @mbggenerated
     */
    public void setSolidContainingContent(Float solidContainingContent) {
        this.solidContainingContent = solidContainingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.weight
     *
     * @return the value of goods_in_process_statistic_ageing.weight
     *
     * @mbggenerated
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.weight
     *
     * @param weight the value for goods_in_process_statistic_ageing.weight
     *
     * @mbggenerated
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.Ni_concentration
     *
     * @return the value of goods_in_process_statistic_ageing.Ni_concentration
     *
     * @mbggenerated
     */
    public Float getNiConcentration() {
        return niConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.Ni_concentration
     *
     * @param niConcentration the value for goods_in_process_statistic_ageing.Ni_concentration
     *
     * @mbggenerated
     */
    public void setNiConcentration(Float niConcentration) {
        this.niConcentration = niConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.Co_concentration
     *
     * @return the value of goods_in_process_statistic_ageing.Co_concentration
     *
     * @mbggenerated
     */
    public Float getCoConcentration() {
        return coConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.Co_concentration
     *
     * @param coConcentration the value for goods_in_process_statistic_ageing.Co_concentration
     *
     * @mbggenerated
     */
    public void setCoConcentration(Float coConcentration) {
        this.coConcentration = coConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.Mn_concentration
     *
     * @return the value of goods_in_process_statistic_ageing.Mn_concentration
     *
     * @mbggenerated
     */
    public Float getMnConcentration() {
        return mnConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.Mn_concentration
     *
     * @param mnConcentration the value for goods_in_process_statistic_ageing.Mn_concentration
     *
     * @mbggenerated
     */
    public void setMnConcentration(Float mnConcentration) {
        this.mnConcentration = mnConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.Ni_metallicity
     *
     * @return the value of goods_in_process_statistic_ageing.Ni_metallicity
     *
     * @mbggenerated
     */
    public Float getNiMetallicity() {
        return niMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.Ni_metallicity
     *
     * @param niMetallicity the value for goods_in_process_statistic_ageing.Ni_metallicity
     *
     * @mbggenerated
     */
    public void setNiMetallicity(Float niMetallicity) {
        this.niMetallicity = niMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.Co_metallicity
     *
     * @return the value of goods_in_process_statistic_ageing.Co_metallicity
     *
     * @mbggenerated
     */
    public Float getCoMetallicity() {
        return coMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.Co_metallicity
     *
     * @param coMetallicity the value for goods_in_process_statistic_ageing.Co_metallicity
     *
     * @mbggenerated
     */
    public void setCoMetallicity(Float coMetallicity) {
        this.coMetallicity = coMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_in_process_statistic_ageing.Mn_metallicity
     *
     * @return the value of goods_in_process_statistic_ageing.Mn_metallicity
     *
     * @mbggenerated
     */
    public Float getMnMetallicity() {
        return mnMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_in_process_statistic_ageing.Mn_metallicity
     *
     * @param mnMetallicity the value for goods_in_process_statistic_ageing.Mn_metallicity
     *
     * @mbggenerated
     */
    public void setMnMetallicity(Float mnMetallicity) {
        this.mnMetallicity = mnMetallicity;
    }
}