package com.jinchi.common.domain;

public class MaterialDeliveryStatisticSingleCrystalLiquor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.statistic_code
     *
     * @mbggenerated
     */
    private Long statisticCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.material_type_code
     *
     * @mbggenerated
     */
    private Integer materialTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.material_code
     *
     * @mbggenerated
     */
    private Integer materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.weights
     *
     * @mbggenerated
     */
    private Float weights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.density
     *
     * @mbggenerated
     */
    private Float density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.ni_concentration
     *
     * @mbggenerated
     */
    private Float niConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.co_concentration
     *
     * @mbggenerated
     */
    private Float coConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.mn_concentration
     *
     * @mbggenerated
     */
    private Float mnConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.ni_metallicity
     *
     * @mbggenerated
     */
    private Float niMetallicity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.co_metallicity
     *
     * @mbggenerated
     */
    private Float coMetallicity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_delivery_statistic_single_crystal_liquor.mn_metallicity
     *
     * @mbggenerated
     */
    private Float mnMetallicity;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_single_crystal_liquor
     *
     * @mbggenerated
     */
    public MaterialDeliveryStatisticSingleCrystalLiquor(Long code, Long statisticCode, Integer materialTypeCode, Integer materialCode, String materialName, Float weights, Float density, Float niConcentration, Float coConcentration, Float mnConcentration, Float niMetallicity, Float coMetallicity, Float mnMetallicity) {
        this.code = code;
        this.statisticCode = statisticCode;
        this.materialTypeCode = materialTypeCode;
        this.materialCode = materialCode;
        this.materialName = materialName;
        this.weights = weights;
        this.density = density;
        this.niConcentration = niConcentration;
        this.coConcentration = coConcentration;
        this.mnConcentration = mnConcentration;
        this.niMetallicity = niMetallicity;
        this.coMetallicity = coMetallicity;
        this.mnMetallicity = mnMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_delivery_statistic_single_crystal_liquor
     *
     * @mbggenerated
     */
    public MaterialDeliveryStatisticSingleCrystalLiquor() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.code
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.code
     *
     * @param code the value for material_delivery_statistic_single_crystal_liquor.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.statistic_code
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.statistic_code
     *
     * @mbggenerated
     */
    public Long getStatisticCode() {
        return statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.statistic_code
     *
     * @param statisticCode the value for material_delivery_statistic_single_crystal_liquor.statistic_code
     *
     * @mbggenerated
     */
    public void setStatisticCode(Long statisticCode) {
        this.statisticCode = statisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.material_type_code
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.material_type_code
     *
     * @mbggenerated
     */
    public Integer getMaterialTypeCode() {
        return materialTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.material_type_code
     *
     * @param materialTypeCode the value for material_delivery_statistic_single_crystal_liquor.material_type_code
     *
     * @mbggenerated
     */
    public void setMaterialTypeCode(Integer materialTypeCode) {
        this.materialTypeCode = materialTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.material_code
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.material_code
     *
     * @mbggenerated
     */
    public Integer getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.material_code
     *
     * @param materialCode the value for material_delivery_statistic_single_crystal_liquor.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(Integer materialCode) {
        this.materialCode = materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.material_name
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.material_name
     *
     * @param materialName the value for material_delivery_statistic_single_crystal_liquor.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.weights
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.weights
     *
     * @mbggenerated
     */
    public Float getWeights() {
        return weights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.weights
     *
     * @param weights the value for material_delivery_statistic_single_crystal_liquor.weights
     *
     * @mbggenerated
     */
    public void setWeights(Float weights) {
        this.weights = weights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.density
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.density
     *
     * @mbggenerated
     */
    public Float getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.density
     *
     * @param density the value for material_delivery_statistic_single_crystal_liquor.density
     *
     * @mbggenerated
     */
    public void setDensity(Float density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.ni_concentration
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.ni_concentration
     *
     * @mbggenerated
     */
    public Float getNiConcentration() {
        return niConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.ni_concentration
     *
     * @param niConcentration the value for material_delivery_statistic_single_crystal_liquor.ni_concentration
     *
     * @mbggenerated
     */
    public void setNiConcentration(Float niConcentration) {
        this.niConcentration = niConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.co_concentration
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.co_concentration
     *
     * @mbggenerated
     */
    public Float getCoConcentration() {
        return coConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.co_concentration
     *
     * @param coConcentration the value for material_delivery_statistic_single_crystal_liquor.co_concentration
     *
     * @mbggenerated
     */
    public void setCoConcentration(Float coConcentration) {
        this.coConcentration = coConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.mn_concentration
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.mn_concentration
     *
     * @mbggenerated
     */
    public Float getMnConcentration() {
        return mnConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.mn_concentration
     *
     * @param mnConcentration the value for material_delivery_statistic_single_crystal_liquor.mn_concentration
     *
     * @mbggenerated
     */
    public void setMnConcentration(Float mnConcentration) {
        this.mnConcentration = mnConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.ni_metallicity
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.ni_metallicity
     *
     * @mbggenerated
     */
    public Float getNiMetallicity() {
        return niMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.ni_metallicity
     *
     * @param niMetallicity the value for material_delivery_statistic_single_crystal_liquor.ni_metallicity
     *
     * @mbggenerated
     */
    public void setNiMetallicity(Float niMetallicity) {
        this.niMetallicity = niMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.co_metallicity
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.co_metallicity
     *
     * @mbggenerated
     */
    public Float getCoMetallicity() {
        return coMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.co_metallicity
     *
     * @param coMetallicity the value for material_delivery_statistic_single_crystal_liquor.co_metallicity
     *
     * @mbggenerated
     */
    public void setCoMetallicity(Float coMetallicity) {
        this.coMetallicity = coMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_delivery_statistic_single_crystal_liquor.mn_metallicity
     *
     * @return the value of material_delivery_statistic_single_crystal_liquor.mn_metallicity
     *
     * @mbggenerated
     */
    public Float getMnMetallicity() {
        return mnMetallicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_delivery_statistic_single_crystal_liquor.mn_metallicity
     *
     * @param mnMetallicity the value for material_delivery_statistic_single_crystal_liquor.mn_metallicity
     *
     * @mbggenerated
     */
    public void setMnMetallicity(Float mnMetallicity) {
        this.mnMetallicity = mnMetallicity;
    }
}