package com.jinchi.common.domain;

public class ProcessParametersHcExceptionDispose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_exception_dispose.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_exception_dispose.process_code
     *
     * @mbggenerated
     */
    private Long processCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_exception_dispose.phenomenon
     *
     * @mbggenerated
     */
    private String phenomenon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_exception_dispose.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_exception_dispose.process_mode
     *
     * @mbggenerated
     */
    private String processMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_exception_dispose.related_production_process
     *
     * @mbggenerated
     */
    private String relatedProductionProcess;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_parameters_hc_exception_dispose
     *
     * @mbggenerated
     */
    public ProcessParametersHcExceptionDispose(Long code, Long processCode, String phenomenon, String reason, String processMode, String relatedProductionProcess) {
        this.code = code;
        this.processCode = processCode;
        this.phenomenon = phenomenon;
        this.reason = reason;
        this.processMode = processMode;
        this.relatedProductionProcess = relatedProductionProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_parameters_hc_exception_dispose
     *
     * @mbggenerated
     */
    public ProcessParametersHcExceptionDispose() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_exception_dispose.code
     *
     * @return the value of process_parameters_hc_exception_dispose.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_exception_dispose.code
     *
     * @param code the value for process_parameters_hc_exception_dispose.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_exception_dispose.process_code
     *
     * @return the value of process_parameters_hc_exception_dispose.process_code
     *
     * @mbggenerated
     */
    public Long getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_exception_dispose.process_code
     *
     * @param processCode the value for process_parameters_hc_exception_dispose.process_code
     *
     * @mbggenerated
     */
    public void setProcessCode(Long processCode) {
        this.processCode = processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_exception_dispose.phenomenon
     *
     * @return the value of process_parameters_hc_exception_dispose.phenomenon
     *
     * @mbggenerated
     */
    public String getPhenomenon() {
        return phenomenon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_exception_dispose.phenomenon
     *
     * @param phenomenon the value for process_parameters_hc_exception_dispose.phenomenon
     *
     * @mbggenerated
     */
    public void setPhenomenon(String phenomenon) {
        this.phenomenon = phenomenon == null ? null : phenomenon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_exception_dispose.reason
     *
     * @return the value of process_parameters_hc_exception_dispose.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_exception_dispose.reason
     *
     * @param reason the value for process_parameters_hc_exception_dispose.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_exception_dispose.process_mode
     *
     * @return the value of process_parameters_hc_exception_dispose.process_mode
     *
     * @mbggenerated
     */
    public String getProcessMode() {
        return processMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_exception_dispose.process_mode
     *
     * @param processMode the value for process_parameters_hc_exception_dispose.process_mode
     *
     * @mbggenerated
     */
    public void setProcessMode(String processMode) {
        this.processMode = processMode == null ? null : processMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_exception_dispose.related_production_process
     *
     * @return the value of process_parameters_hc_exception_dispose.related_production_process
     *
     * @mbggenerated
     */
    public String getRelatedProductionProcess() {
        return relatedProductionProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_exception_dispose.related_production_process
     *
     * @param relatedProductionProcess the value for process_parameters_hc_exception_dispose.related_production_process
     *
     * @mbggenerated
     */
    public void setRelatedProductionProcess(String relatedProductionProcess) {
        this.relatedProductionProcess = relatedProductionProcess == null ? null : relatedProductionProcess.trim();
    }
}