package com.jinchi.common.domain;

public class ProcessParametersHcIntermediateGoodsStd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_intermediate_goods_std.code
     *
     * @mbggenerated
     */
    private Long code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_intermediate_goods_std.process_code
     *
     * @mbggenerated
     */
    private Long processCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_intermediate_goods_std.item
     *
     * @mbggenerated
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_intermediate_goods_std.sample_place
     *
     * @mbggenerated
     */
    private String samplePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_intermediate_goods_std.frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_parameters_hc_intermediate_goods_std.standards
     *
     * @mbggenerated
     */
    private String standards;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_parameters_hc_intermediate_goods_std
     *
     * @mbggenerated
     */
    public ProcessParametersHcIntermediateGoodsStd(Long code, Long processCode, String item, String samplePlace, String frequency, String standards) {
        this.code = code;
        this.processCode = processCode;
        this.item = item;
        this.samplePlace = samplePlace;
        this.frequency = frequency;
        this.standards = standards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_parameters_hc_intermediate_goods_std
     *
     * @mbggenerated
     */
    public ProcessParametersHcIntermediateGoodsStd() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_intermediate_goods_std.code
     *
     * @return the value of process_parameters_hc_intermediate_goods_std.code
     *
     * @mbggenerated
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_intermediate_goods_std.code
     *
     * @param code the value for process_parameters_hc_intermediate_goods_std.code
     *
     * @mbggenerated
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_intermediate_goods_std.process_code
     *
     * @return the value of process_parameters_hc_intermediate_goods_std.process_code
     *
     * @mbggenerated
     */
    public Long getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_intermediate_goods_std.process_code
     *
     * @param processCode the value for process_parameters_hc_intermediate_goods_std.process_code
     *
     * @mbggenerated
     */
    public void setProcessCode(Long processCode) {
        this.processCode = processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_intermediate_goods_std.item
     *
     * @return the value of process_parameters_hc_intermediate_goods_std.item
     *
     * @mbggenerated
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_intermediate_goods_std.item
     *
     * @param item the value for process_parameters_hc_intermediate_goods_std.item
     *
     * @mbggenerated
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_intermediate_goods_std.sample_place
     *
     * @return the value of process_parameters_hc_intermediate_goods_std.sample_place
     *
     * @mbggenerated
     */
    public String getSamplePlace() {
        return samplePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_intermediate_goods_std.sample_place
     *
     * @param samplePlace the value for process_parameters_hc_intermediate_goods_std.sample_place
     *
     * @mbggenerated
     */
    public void setSamplePlace(String samplePlace) {
        this.samplePlace = samplePlace == null ? null : samplePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_intermediate_goods_std.frequency
     *
     * @return the value of process_parameters_hc_intermediate_goods_std.frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_intermediate_goods_std.frequency
     *
     * @param frequency the value for process_parameters_hc_intermediate_goods_std.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_parameters_hc_intermediate_goods_std.standards
     *
     * @return the value of process_parameters_hc_intermediate_goods_std.standards
     *
     * @mbggenerated
     */
    public String getStandards() {
        return standards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_parameters_hc_intermediate_goods_std.standards
     *
     * @param standards the value for process_parameters_hc_intermediate_goods_std.standards
     *
     * @mbggenerated
     */
    public void setStandards(String standards) {
        this.standards = standards == null ? null : standards.trim();
    }
}