package com.jinchi.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SwmsStockOutRecordHeadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public SwmsStockOutRecordHeadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdIsNull() {
            addCriterion("application_form_id is null");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdIsNotNull() {
            addCriterion("application_form_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdEqualTo(Long value) {
            addCriterion("application_form_id =", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdNotEqualTo(Long value) {
            addCriterion("application_form_id <>", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdGreaterThan(Long value) {
            addCriterion("application_form_id >", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdGreaterThanOrEqualTo(Long value) {
            addCriterion("application_form_id >=", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdLessThan(Long value) {
            addCriterion("application_form_id <", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdLessThanOrEqualTo(Long value) {
            addCriterion("application_form_id <=", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdIn(List<Long> values) {
            addCriterion("application_form_id in", values, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdNotIn(List<Long> values) {
            addCriterion("application_form_id not in", values, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdBetween(Long value1, Long value2) {
            addCriterion("application_form_id between", value1, value2, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdNotBetween(Long value1, Long value2) {
            addCriterion("application_form_id not between", value1, value2, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeIsNull() {
            addCriterion("stock_out_record_head_code is null");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeIsNotNull() {
            addCriterion("stock_out_record_head_code is not null");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeEqualTo(Long value) {
            addCriterion("stock_out_record_head_code =", value, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeNotEqualTo(Long value) {
            addCriterion("stock_out_record_head_code <>", value, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeGreaterThan(Long value) {
            addCriterion("stock_out_record_head_code >", value, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("stock_out_record_head_code >=", value, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeLessThan(Long value) {
            addCriterion("stock_out_record_head_code <", value, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeLessThanOrEqualTo(Long value) {
            addCriterion("stock_out_record_head_code <=", value, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeIn(List<Long> values) {
            addCriterion("stock_out_record_head_code in", values, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeNotIn(List<Long> values) {
            addCriterion("stock_out_record_head_code not in", values, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeBetween(Long value1, Long value2) {
            addCriterion("stock_out_record_head_code between", value1, value2, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andStockOutRecordHeadCodeNotBetween(Long value1, Long value2) {
            addCriterion("stock_out_record_head_code not between", value1, value2, "stockOutRecordHeadCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNull() {
            addCriterion("dept_code is null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNotNull() {
            addCriterion("dept_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeEqualTo(Integer value) {
            addCriterion("dept_code =", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotEqualTo(Integer value) {
            addCriterion("dept_code <>", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThan(Integer value) {
            addCriterion("dept_code >", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_code >=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThan(Integer value) {
            addCriterion("dept_code <", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThanOrEqualTo(Integer value) {
            addCriterion("dept_code <=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIn(List<Integer> values) {
            addCriterion("dept_code in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotIn(List<Integer> values) {
            addCriterion("dept_code not in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeBetween(Integer value1, Integer value2) {
            addCriterion("dept_code between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_code not between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeIsNull() {
            addCriterion("hf_line_code is null");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeIsNotNull() {
            addCriterion("hf_line_code is not null");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeEqualTo(Integer value) {
            addCriterion("hf_line_code =", value, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeNotEqualTo(Integer value) {
            addCriterion("hf_line_code <>", value, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeGreaterThan(Integer value) {
            addCriterion("hf_line_code >", value, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("hf_line_code >=", value, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeLessThan(Integer value) {
            addCriterion("hf_line_code <", value, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeLessThanOrEqualTo(Integer value) {
            addCriterion("hf_line_code <=", value, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeIn(List<Integer> values) {
            addCriterion("hf_line_code in", values, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeNotIn(List<Integer> values) {
            addCriterion("hf_line_code not in", values, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeBetween(Integer value1, Integer value2) {
            addCriterion("hf_line_code between", value1, value2, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andHfLineCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("hf_line_code not between", value1, value2, "hfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeIsNull() {
            addCriterion("sf_line_code is null");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeIsNotNull() {
            addCriterion("sf_line_code is not null");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeEqualTo(Integer value) {
            addCriterion("sf_line_code =", value, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeNotEqualTo(Integer value) {
            addCriterion("sf_line_code <>", value, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeGreaterThan(Integer value) {
            addCriterion("sf_line_code >", value, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sf_line_code >=", value, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeLessThan(Integer value) {
            addCriterion("sf_line_code <", value, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeLessThanOrEqualTo(Integer value) {
            addCriterion("sf_line_code <=", value, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeIn(List<Integer> values) {
            addCriterion("sf_line_code in", values, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeNotIn(List<Integer> values) {
            addCriterion("sf_line_code not in", values, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeBetween(Integer value1, Integer value2) {
            addCriterion("sf_line_code between", value1, value2, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andSfLineCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("sf_line_code not between", value1, value2, "sfLineCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeIsNull() {
            addCriterion("delivery_type_code is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeIsNotNull() {
            addCriterion("delivery_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeEqualTo(Integer value) {
            addCriterion("delivery_type_code =", value, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeNotEqualTo(Integer value) {
            addCriterion("delivery_type_code <>", value, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeGreaterThan(Integer value) {
            addCriterion("delivery_type_code >", value, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("delivery_type_code >=", value, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeLessThan(Integer value) {
            addCriterion("delivery_type_code <", value, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeLessThanOrEqualTo(Integer value) {
            addCriterion("delivery_type_code <=", value, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeIn(List<Integer> values) {
            addCriterion("delivery_type_code in", values, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeNotIn(List<Integer> values) {
            addCriterion("delivery_type_code not in", values, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeBetween(Integer value1, Integer value2) {
            addCriterion("delivery_type_code between", value1, value2, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryTypeCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("delivery_type_code not between", value1, value2, "deliveryTypeCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeIsNull() {
            addCriterion("delivery_address_code is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeIsNotNull() {
            addCriterion("delivery_address_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeEqualTo(Integer value) {
            addCriterion("delivery_address_code =", value, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeNotEqualTo(Integer value) {
            addCriterion("delivery_address_code <>", value, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeGreaterThan(Integer value) {
            addCriterion("delivery_address_code >", value, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("delivery_address_code >=", value, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeLessThan(Integer value) {
            addCriterion("delivery_address_code <", value, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeLessThanOrEqualTo(Integer value) {
            addCriterion("delivery_address_code <=", value, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeIn(List<Integer> values) {
            addCriterion("delivery_address_code in", values, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeNotIn(List<Integer> values) {
            addCriterion("delivery_address_code not in", values, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeBetween(Integer value1, Integer value2) {
            addCriterion("delivery_address_code between", value1, value2, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryAddressCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("delivery_address_code not between", value1, value2, "deliveryAddressCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdIsNull() {
            addCriterion("material_sub_type_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdIsNotNull() {
            addCriterion("material_sub_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdEqualTo(Integer value) {
            addCriterion("material_sub_type_id =", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdNotEqualTo(Integer value) {
            addCriterion("material_sub_type_id <>", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdGreaterThan(Integer value) {
            addCriterion("material_sub_type_id >", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_sub_type_id >=", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdLessThan(Integer value) {
            addCriterion("material_sub_type_id <", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_sub_type_id <=", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdIn(List<Integer> values) {
            addCriterion("material_sub_type_id in", values, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdNotIn(List<Integer> values) {
            addCriterion("material_sub_type_id not in", values, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("material_sub_type_id between", value1, value2, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_sub_type_id not between", value1, value2, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdIsNull() {
            addCriterion("material_workshop_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdIsNotNull() {
            addCriterion("material_workshop_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdEqualTo(Integer value) {
            addCriterion("material_workshop_id =", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdNotEqualTo(Integer value) {
            addCriterion("material_workshop_id <>", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdGreaterThan(Integer value) {
            addCriterion("material_workshop_id >", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_workshop_id >=", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdLessThan(Integer value) {
            addCriterion("material_workshop_id <", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_workshop_id <=", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdIn(List<Integer> values) {
            addCriterion("material_workshop_id in", values, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdNotIn(List<Integer> values) {
            addCriterion("material_workshop_id not in", values, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdBetween(Integer value1, Integer value2) {
            addCriterion("material_workshop_id between", value1, value2, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_workshop_id not between", value1, value2, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdIsNull() {
            addCriterion("created_person_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdIsNotNull() {
            addCriterion("created_person_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdEqualTo(Integer value) {
            addCriterion("created_person_id =", value, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdNotEqualTo(Integer value) {
            addCriterion("created_person_id <>", value, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdGreaterThan(Integer value) {
            addCriterion("created_person_id >", value, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_person_id >=", value, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdLessThan(Integer value) {
            addCriterion("created_person_id <", value, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdLessThanOrEqualTo(Integer value) {
            addCriterion("created_person_id <=", value, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdIn(List<Integer> values) {
            addCriterion("created_person_id in", values, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdNotIn(List<Integer> values) {
            addCriterion("created_person_id not in", values, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdBetween(Integer value1, Integer value2) {
            addCriterion("created_person_id between", value1, value2, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("created_person_id not between", value1, value2, "createdPersonId");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIsNull() {
            addCriterion("created_person is null");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIsNotNull() {
            addCriterion("created_person is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonEqualTo(String value) {
            addCriterion("created_person =", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonNotEqualTo(String value) {
            addCriterion("created_person <>", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonGreaterThan(String value) {
            addCriterion("created_person >", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonGreaterThanOrEqualTo(String value) {
            addCriterion("created_person >=", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonLessThan(String value) {
            addCriterion("created_person <", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonLessThanOrEqualTo(String value) {
            addCriterion("created_person <=", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonLike(String value) {
            addCriterion("created_person like", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonNotLike(String value) {
            addCriterion("created_person not like", value, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonIn(List<String> values) {
            addCriterion("created_person in", values, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonNotIn(List<String> values) {
            addCriterion("created_person not in", values, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonBetween(String value1, String value2) {
            addCriterion("created_person between", value1, value2, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCreatedPersonNotBetween(String value1, String value2) {
            addCriterion("created_person not between", value1, value2, "createdPerson");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeIsNull() {
            addCriterion("completion_time is null");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeIsNotNull() {
            addCriterion("completion_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeEqualTo(Date value) {
            addCriterion("completion_time =", value, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeNotEqualTo(Date value) {
            addCriterion("completion_time <>", value, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeGreaterThan(Date value) {
            addCriterion("completion_time >", value, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("completion_time >=", value, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeLessThan(Date value) {
            addCriterion("completion_time <", value, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeLessThanOrEqualTo(Date value) {
            addCriterion("completion_time <=", value, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeIn(List<Date> values) {
            addCriterion("completion_time in", values, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeNotIn(List<Date> values) {
            addCriterion("completion_time not in", values, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeBetween(Date value1, Date value2) {
            addCriterion("completion_time between", value1, value2, "completionTime");
            return (Criteria) this;
        }

        public Criteria andCompletionTimeNotBetween(Date value1, Date value2) {
            addCriterion("completion_time not between", value1, value2, "completionTime");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusIsNull() {
            addCriterion("material_status is null");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusIsNotNull() {
            addCriterion("material_status is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusEqualTo(Byte value) {
            addCriterion("material_status =", value, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusNotEqualTo(Byte value) {
            addCriterion("material_status <>", value, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusGreaterThan(Byte value) {
            addCriterion("material_status >", value, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("material_status >=", value, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusLessThan(Byte value) {
            addCriterion("material_status <", value, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusLessThanOrEqualTo(Byte value) {
            addCriterion("material_status <=", value, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusIn(List<Byte> values) {
            addCriterion("material_status in", values, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusNotIn(List<Byte> values) {
            addCriterion("material_status not in", values, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusBetween(Byte value1, Byte value2) {
            addCriterion("material_status between", value1, value2, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andMaterialStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("material_status not between", value1, value2, "materialStatus");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNull() {
            addCriterion("sys_flag is null");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNotNull() {
            addCriterion("sys_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSysFlagEqualTo(Boolean value) {
            addCriterion("sys_flag =", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotEqualTo(Boolean value) {
            addCriterion("sys_flag <>", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThan(Boolean value) {
            addCriterion("sys_flag >", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sys_flag >=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThan(Boolean value) {
            addCriterion("sys_flag <", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("sys_flag <=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagIn(List<Boolean> values) {
            addCriterion("sys_flag in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotIn(List<Boolean> values) {
            addCriterion("sys_flag not in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("sys_flag between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sys_flag not between", value1, value2, "sysFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SWMS_stock_out_record_head
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}