package com.jinchi.common.domain;

import java.util.Date;

public class SwmsStockInLedgers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.stock_in_record_id
     *
     * @mbggenerated
     */
    private Long stockInRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_code
     *
     * @mbggenerated
     */
    private String materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_batch
     *
     * @mbggenerated
     */
    private String materialBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_type_id
     *
     * @mbggenerated
     */
    private Integer materialTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_sub_type_id
     *
     * @mbggenerated
     */
    private Integer materialSubTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_workshop_id
     *
     * @mbggenerated
     */
    private Integer materialWorkshopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_name_code
     *
     * @mbggenerated
     */
    private Integer materialNameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_supplier_code
     *
     * @mbggenerated
     */
    private Integer materialSupplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.bag_num
     *
     * @mbggenerated
     */
    private Integer bagNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.weight
     *
     * @mbggenerated
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.measure_unit
     *
     * @mbggenerated
     */
    private String measureUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.created_person
     *
     * @mbggenerated
     */
    private String createdPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWMS_stock_in_ledgers.material_status
     *
     * @mbggenerated
     */
    private Byte materialStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers
     *
     * @mbggenerated
     */
    public SwmsStockInLedgers(Long id, Long stockInRecordId, String materialCode, String materialBatch, Integer materialTypeId, Integer materialSubTypeId, Integer materialWorkshopId, Integer materialNameCode, Integer materialSupplierCode, String materialName, Integer bagNum, Float weight, String measureUnit, Date createdTime, String createdPerson, Byte materialStatus) {
        this.id = id;
        this.stockInRecordId = stockInRecordId;
        this.materialCode = materialCode;
        this.materialBatch = materialBatch;
        this.materialTypeId = materialTypeId;
        this.materialSubTypeId = materialSubTypeId;
        this.materialWorkshopId = materialWorkshopId;
        this.materialNameCode = materialNameCode;
        this.materialSupplierCode = materialSupplierCode;
        this.materialName = materialName;
        this.bagNum = bagNum;
        this.weight = weight;
        this.measureUnit = measureUnit;
        this.createdTime = createdTime;
        this.createdPerson = createdPerson;
        this.materialStatus = materialStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers
     *
     * @mbggenerated
     */
    public SwmsStockInLedgers() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.id
     *
     * @return the value of SWMS_stock_in_ledgers.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.id
     *
     * @param id the value for SWMS_stock_in_ledgers.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.stock_in_record_id
     *
     * @return the value of SWMS_stock_in_ledgers.stock_in_record_id
     *
     * @mbggenerated
     */
    public Long getStockInRecordId() {
        return stockInRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.stock_in_record_id
     *
     * @param stockInRecordId the value for SWMS_stock_in_ledgers.stock_in_record_id
     *
     * @mbggenerated
     */
    public void setStockInRecordId(Long stockInRecordId) {
        this.stockInRecordId = stockInRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_code
     *
     * @return the value of SWMS_stock_in_ledgers.material_code
     *
     * @mbggenerated
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_code
     *
     * @param materialCode the value for SWMS_stock_in_ledgers.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_batch
     *
     * @return the value of SWMS_stock_in_ledgers.material_batch
     *
     * @mbggenerated
     */
    public String getMaterialBatch() {
        return materialBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_batch
     *
     * @param materialBatch the value for SWMS_stock_in_ledgers.material_batch
     *
     * @mbggenerated
     */
    public void setMaterialBatch(String materialBatch) {
        this.materialBatch = materialBatch == null ? null : materialBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_type_id
     *
     * @return the value of SWMS_stock_in_ledgers.material_type_id
     *
     * @mbggenerated
     */
    public Integer getMaterialTypeId() {
        return materialTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_type_id
     *
     * @param materialTypeId the value for SWMS_stock_in_ledgers.material_type_id
     *
     * @mbggenerated
     */
    public void setMaterialTypeId(Integer materialTypeId) {
        this.materialTypeId = materialTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_sub_type_id
     *
     * @return the value of SWMS_stock_in_ledgers.material_sub_type_id
     *
     * @mbggenerated
     */
    public Integer getMaterialSubTypeId() {
        return materialSubTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_sub_type_id
     *
     * @param materialSubTypeId the value for SWMS_stock_in_ledgers.material_sub_type_id
     *
     * @mbggenerated
     */
    public void setMaterialSubTypeId(Integer materialSubTypeId) {
        this.materialSubTypeId = materialSubTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_workshop_id
     *
     * @return the value of SWMS_stock_in_ledgers.material_workshop_id
     *
     * @mbggenerated
     */
    public Integer getMaterialWorkshopId() {
        return materialWorkshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_workshop_id
     *
     * @param materialWorkshopId the value for SWMS_stock_in_ledgers.material_workshop_id
     *
     * @mbggenerated
     */
    public void setMaterialWorkshopId(Integer materialWorkshopId) {
        this.materialWorkshopId = materialWorkshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_name_code
     *
     * @return the value of SWMS_stock_in_ledgers.material_name_code
     *
     * @mbggenerated
     */
    public Integer getMaterialNameCode() {
        return materialNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_name_code
     *
     * @param materialNameCode the value for SWMS_stock_in_ledgers.material_name_code
     *
     * @mbggenerated
     */
    public void setMaterialNameCode(Integer materialNameCode) {
        this.materialNameCode = materialNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_supplier_code
     *
     * @return the value of SWMS_stock_in_ledgers.material_supplier_code
     *
     * @mbggenerated
     */
    public Integer getMaterialSupplierCode() {
        return materialSupplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_supplier_code
     *
     * @param materialSupplierCode the value for SWMS_stock_in_ledgers.material_supplier_code
     *
     * @mbggenerated
     */
    public void setMaterialSupplierCode(Integer materialSupplierCode) {
        this.materialSupplierCode = materialSupplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_name
     *
     * @return the value of SWMS_stock_in_ledgers.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_name
     *
     * @param materialName the value for SWMS_stock_in_ledgers.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.bag_num
     *
     * @return the value of SWMS_stock_in_ledgers.bag_num
     *
     * @mbggenerated
     */
    public Integer getBagNum() {
        return bagNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.bag_num
     *
     * @param bagNum the value for SWMS_stock_in_ledgers.bag_num
     *
     * @mbggenerated
     */
    public void setBagNum(Integer bagNum) {
        this.bagNum = bagNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.weight
     *
     * @return the value of SWMS_stock_in_ledgers.weight
     *
     * @mbggenerated
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.weight
     *
     * @param weight the value for SWMS_stock_in_ledgers.weight
     *
     * @mbggenerated
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.measure_unit
     *
     * @return the value of SWMS_stock_in_ledgers.measure_unit
     *
     * @mbggenerated
     */
    public String getMeasureUnit() {
        return measureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.measure_unit
     *
     * @param measureUnit the value for SWMS_stock_in_ledgers.measure_unit
     *
     * @mbggenerated
     */
    public void setMeasureUnit(String measureUnit) {
        this.measureUnit = measureUnit == null ? null : measureUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.created_time
     *
     * @return the value of SWMS_stock_in_ledgers.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.created_time
     *
     * @param createdTime the value for SWMS_stock_in_ledgers.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.created_person
     *
     * @return the value of SWMS_stock_in_ledgers.created_person
     *
     * @mbggenerated
     */
    public String getCreatedPerson() {
        return createdPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.created_person
     *
     * @param createdPerson the value for SWMS_stock_in_ledgers.created_person
     *
     * @mbggenerated
     */
    public void setCreatedPerson(String createdPerson) {
        this.createdPerson = createdPerson == null ? null : createdPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWMS_stock_in_ledgers.material_status
     *
     * @return the value of SWMS_stock_in_ledgers.material_status
     *
     * @mbggenerated
     */
    public Byte getMaterialStatus() {
        return materialStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWMS_stock_in_ledgers.material_status
     *
     * @param materialStatus the value for SWMS_stock_in_ledgers.material_status
     *
     * @mbggenerated
     */
    public void setMaterialStatus(Byte materialStatus) {
        this.materialStatus = materialStatus;
    }
}