package com.jinchi.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SwmsStockInLedgersDayReportsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public SwmsStockInLedgersDayReportsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchIsNull() {
            addCriterion("material_batch is null");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchIsNotNull() {
            addCriterion("material_batch is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchEqualTo(String value) {
            addCriterion("material_batch =", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchNotEqualTo(String value) {
            addCriterion("material_batch <>", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchGreaterThan(String value) {
            addCriterion("material_batch >", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchGreaterThanOrEqualTo(String value) {
            addCriterion("material_batch >=", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchLessThan(String value) {
            addCriterion("material_batch <", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchLessThanOrEqualTo(String value) {
            addCriterion("material_batch <=", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchLike(String value) {
            addCriterion("material_batch like", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchNotLike(String value) {
            addCriterion("material_batch not like", value, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchIn(List<String> values) {
            addCriterion("material_batch in", values, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchNotIn(List<String> values) {
            addCriterion("material_batch not in", values, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchBetween(String value1, String value2) {
            addCriterion("material_batch between", value1, value2, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialBatchNotBetween(String value1, String value2) {
            addCriterion("material_batch not between", value1, value2, "materialBatch");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdIsNull() {
            addCriterion("material_type_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdIsNotNull() {
            addCriterion("material_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdEqualTo(Integer value) {
            addCriterion("material_type_id =", value, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdNotEqualTo(Integer value) {
            addCriterion("material_type_id <>", value, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdGreaterThan(Integer value) {
            addCriterion("material_type_id >", value, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_type_id >=", value, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdLessThan(Integer value) {
            addCriterion("material_type_id <", value, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_type_id <=", value, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdIn(List<Integer> values) {
            addCriterion("material_type_id in", values, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdNotIn(List<Integer> values) {
            addCriterion("material_type_id not in", values, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("material_type_id between", value1, value2, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_type_id not between", value1, value2, "materialTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdIsNull() {
            addCriterion("material_sub_type_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdIsNotNull() {
            addCriterion("material_sub_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdEqualTo(Integer value) {
            addCriterion("material_sub_type_id =", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdNotEqualTo(Integer value) {
            addCriterion("material_sub_type_id <>", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdGreaterThan(Integer value) {
            addCriterion("material_sub_type_id >", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_sub_type_id >=", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdLessThan(Integer value) {
            addCriterion("material_sub_type_id <", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_sub_type_id <=", value, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdIn(List<Integer> values) {
            addCriterion("material_sub_type_id in", values, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdNotIn(List<Integer> values) {
            addCriterion("material_sub_type_id not in", values, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("material_sub_type_id between", value1, value2, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialSubTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_sub_type_id not between", value1, value2, "materialSubTypeId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdIsNull() {
            addCriterion("material_workshop_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdIsNotNull() {
            addCriterion("material_workshop_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdEqualTo(Integer value) {
            addCriterion("material_workshop_id =", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdNotEqualTo(Integer value) {
            addCriterion("material_workshop_id <>", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdGreaterThan(Integer value) {
            addCriterion("material_workshop_id >", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_workshop_id >=", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdLessThan(Integer value) {
            addCriterion("material_workshop_id <", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_workshop_id <=", value, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdIn(List<Integer> values) {
            addCriterion("material_workshop_id in", values, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdNotIn(List<Integer> values) {
            addCriterion("material_workshop_id not in", values, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdBetween(Integer value1, Integer value2) {
            addCriterion("material_workshop_id between", value1, value2, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialWorkshopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_workshop_id not between", value1, value2, "materialWorkshopId");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeIsNull() {
            addCriterion("material_name_code is null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeIsNotNull() {
            addCriterion("material_name_code is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeEqualTo(Integer value) {
            addCriterion("material_name_code =", value, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeNotEqualTo(Integer value) {
            addCriterion("material_name_code <>", value, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeGreaterThan(Integer value) {
            addCriterion("material_name_code >", value, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_name_code >=", value, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeLessThan(Integer value) {
            addCriterion("material_name_code <", value, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeLessThanOrEqualTo(Integer value) {
            addCriterion("material_name_code <=", value, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeIn(List<Integer> values) {
            addCriterion("material_name_code in", values, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeNotIn(List<Integer> values) {
            addCriterion("material_name_code not in", values, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeBetween(Integer value1, Integer value2) {
            addCriterion("material_name_code between", value1, value2, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("material_name_code not between", value1, value2, "materialNameCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeIsNull() {
            addCriterion("material_supplier_code is null");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeIsNotNull() {
            addCriterion("material_supplier_code is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeEqualTo(Integer value) {
            addCriterion("material_supplier_code =", value, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeNotEqualTo(Integer value) {
            addCriterion("material_supplier_code <>", value, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeGreaterThan(Integer value) {
            addCriterion("material_supplier_code >", value, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_supplier_code >=", value, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeLessThan(Integer value) {
            addCriterion("material_supplier_code <", value, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeLessThanOrEqualTo(Integer value) {
            addCriterion("material_supplier_code <=", value, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeIn(List<Integer> values) {
            addCriterion("material_supplier_code in", values, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeNotIn(List<Integer> values) {
            addCriterion("material_supplier_code not in", values, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeBetween(Integer value1, Integer value2) {
            addCriterion("material_supplier_code between", value1, value2, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialSupplierCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("material_supplier_code not between", value1, value2, "materialSupplierCode");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNull() {
            addCriterion("material_name is null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNotNull() {
            addCriterion("material_name is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameEqualTo(String value) {
            addCriterion("material_name =", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotEqualTo(String value) {
            addCriterion("material_name <>", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThan(String value) {
            addCriterion("material_name >", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
            addCriterion("material_name >=", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThan(String value) {
            addCriterion("material_name <", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThanOrEqualTo(String value) {
            addCriterion("material_name <=", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLike(String value) {
            addCriterion("material_name like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotLike(String value) {
            addCriterion("material_name not like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIn(List<String> values) {
            addCriterion("material_name in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotIn(List<String> values) {
            addCriterion("material_name not in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameBetween(String value1, String value2) {
            addCriterion("material_name between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotBetween(String value1, String value2) {
            addCriterion("material_name not between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIsNull() {
            addCriterion("check_status is null");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIsNotNull() {
            addCriterion("check_status is not null");
            return (Criteria) this;
        }

        public Criteria andCheckStatusEqualTo(Byte value) {
            addCriterion("check_status =", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotEqualTo(Byte value) {
            addCriterion("check_status <>", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusGreaterThan(Byte value) {
            addCriterion("check_status >", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("check_status >=", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusLessThan(Byte value) {
            addCriterion("check_status <", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusLessThanOrEqualTo(Byte value) {
            addCriterion("check_status <=", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIn(List<Byte> values) {
            addCriterion("check_status in", values, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotIn(List<Byte> values) {
            addCriterion("check_status not in", values, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusBetween(Byte value1, Byte value2) {
            addCriterion("check_status between", value1, value2, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("check_status not between", value1, value2, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Float value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Float value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Float value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Float value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Float value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Float> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Float> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Float value1, Float value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Float value1, Float value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitIsNull() {
            addCriterion("measure_unit is null");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitIsNotNull() {
            addCriterion("measure_unit is not null");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitEqualTo(String value) {
            addCriterion("measure_unit =", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotEqualTo(String value) {
            addCriterion("measure_unit <>", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitGreaterThan(String value) {
            addCriterion("measure_unit >", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitGreaterThanOrEqualTo(String value) {
            addCriterion("measure_unit >=", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitLessThan(String value) {
            addCriterion("measure_unit <", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitLessThanOrEqualTo(String value) {
            addCriterion("measure_unit <=", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitLike(String value) {
            addCriterion("measure_unit like", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotLike(String value) {
            addCriterion("measure_unit not like", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitIn(List<String> values) {
            addCriterion("measure_unit in", values, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotIn(List<String> values) {
            addCriterion("measure_unit not in", values, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitBetween(String value1, String value2) {
            addCriterion("measure_unit between", value1, value2, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotBetween(String value1, String value2) {
            addCriterion("measure_unit not between", value1, value2, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andBagCountsIsNull() {
            addCriterion("bag_counts is null");
            return (Criteria) this;
        }

        public Criteria andBagCountsIsNotNull() {
            addCriterion("bag_counts is not null");
            return (Criteria) this;
        }

        public Criteria andBagCountsEqualTo(Byte value) {
            addCriterion("bag_counts =", value, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsNotEqualTo(Byte value) {
            addCriterion("bag_counts <>", value, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsGreaterThan(Byte value) {
            addCriterion("bag_counts >", value, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsGreaterThanOrEqualTo(Byte value) {
            addCriterion("bag_counts >=", value, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsLessThan(Byte value) {
            addCriterion("bag_counts <", value, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsLessThanOrEqualTo(Byte value) {
            addCriterion("bag_counts <=", value, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsIn(List<Byte> values) {
            addCriterion("bag_counts in", values, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsNotIn(List<Byte> values) {
            addCriterion("bag_counts not in", values, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsBetween(Byte value1, Byte value2) {
            addCriterion("bag_counts between", value1, value2, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andBagCountsNotBetween(Byte value1, Byte value2) {
            addCriterion("bag_counts not between", value1, value2, "bagCounts");
            return (Criteria) this;
        }

        public Criteria andCreatedDayIsNull() {
            addCriterion("created_day is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDayIsNotNull() {
            addCriterion("created_day is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDayEqualTo(Date value) {
            addCriterion("created_day =", value, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayNotEqualTo(Date value) {
            addCriterion("created_day <>", value, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayGreaterThan(Date value) {
            addCriterion("created_day >", value, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayGreaterThanOrEqualTo(Date value) {
            addCriterion("created_day >=", value, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayLessThan(Date value) {
            addCriterion("created_day <", value, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayLessThanOrEqualTo(Date value) {
            addCriterion("created_day <=", value, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayIn(List<Date> values) {
            addCriterion("created_day in", values, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayNotIn(List<Date> values) {
            addCriterion("created_day not in", values, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayBetween(Date value1, Date value2) {
            addCriterion("created_day between", value1, value2, "createdDay");
            return (Criteria) this;
        }

        public Criteria andCreatedDayNotBetween(Date value1, Date value2) {
            addCriterion("created_day not between", value1, value2, "createdDay");
            return (Criteria) this;
        }

        public Criteria andOutDayIsNull() {
            addCriterion("out_day is null");
            return (Criteria) this;
        }

        public Criteria andOutDayIsNotNull() {
            addCriterion("out_day is not null");
            return (Criteria) this;
        }

        public Criteria andOutDayEqualTo(Date value) {
            addCriterion("out_day =", value, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayNotEqualTo(Date value) {
            addCriterion("out_day <>", value, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayGreaterThan(Date value) {
            addCriterion("out_day >", value, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayGreaterThanOrEqualTo(Date value) {
            addCriterion("out_day >=", value, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayLessThan(Date value) {
            addCriterion("out_day <", value, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayLessThanOrEqualTo(Date value) {
            addCriterion("out_day <=", value, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayIn(List<Date> values) {
            addCriterion("out_day in", values, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayNotIn(List<Date> values) {
            addCriterion("out_day not in", values, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayBetween(Date value1, Date value2) {
            addCriterion("out_day between", value1, value2, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutDayNotBetween(Date value1, Date value2) {
            addCriterion("out_day not between", value1, value2, "outDay");
            return (Criteria) this;
        }

        public Criteria andOutWeightIsNull() {
            addCriterion("out_weight is null");
            return (Criteria) this;
        }

        public Criteria andOutWeightIsNotNull() {
            addCriterion("out_weight is not null");
            return (Criteria) this;
        }

        public Criteria andOutWeightEqualTo(Float value) {
            addCriterion("out_weight =", value, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightNotEqualTo(Float value) {
            addCriterion("out_weight <>", value, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightGreaterThan(Float value) {
            addCriterion("out_weight >", value, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("out_weight >=", value, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightLessThan(Float value) {
            addCriterion("out_weight <", value, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightLessThanOrEqualTo(Float value) {
            addCriterion("out_weight <=", value, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightIn(List<Float> values) {
            addCriterion("out_weight in", values, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightNotIn(List<Float> values) {
            addCriterion("out_weight not in", values, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightBetween(Float value1, Float value2) {
            addCriterion("out_weight between", value1, value2, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutWeightNotBetween(Float value1, Float value2) {
            addCriterion("out_weight not between", value1, value2, "outWeight");
            return (Criteria) this;
        }

        public Criteria andOutCountsIsNull() {
            addCriterion("out_counts is null");
            return (Criteria) this;
        }

        public Criteria andOutCountsIsNotNull() {
            addCriterion("out_counts is not null");
            return (Criteria) this;
        }

        public Criteria andOutCountsEqualTo(Byte value) {
            addCriterion("out_counts =", value, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsNotEqualTo(Byte value) {
            addCriterion("out_counts <>", value, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsGreaterThan(Byte value) {
            addCriterion("out_counts >", value, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsGreaterThanOrEqualTo(Byte value) {
            addCriterion("out_counts >=", value, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsLessThan(Byte value) {
            addCriterion("out_counts <", value, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsLessThanOrEqualTo(Byte value) {
            addCriterion("out_counts <=", value, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsIn(List<Byte> values) {
            addCriterion("out_counts in", values, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsNotIn(List<Byte> values) {
            addCriterion("out_counts not in", values, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsBetween(Byte value1, Byte value2) {
            addCriterion("out_counts between", value1, value2, "outCounts");
            return (Criteria) this;
        }

        public Criteria andOutCountsNotBetween(Byte value1, Byte value2) {
            addCriterion("out_counts not between", value1, value2, "outCounts");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Boolean value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Boolean value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Boolean value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Boolean value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Boolean> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Boolean> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SWMS_stock_in_ledgers_day_reports
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}