server:
  port: 8099
  servlet:
    context-path:
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.190.161:8090/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://175.6.122.21:10088/jc_repo_db?userUnicode=true&characterEncoding=UTF8&useSSL=false&useAffectedRows=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: 123456
  application:
    name: REPOAPI-SERVICE

feign:
  hystrix:
    enabled: true
schedule:
  enable: true
